### ISSUE TITLE
Zopfli algorithm does not work

### ISSUE THREAD

**Issue by leo-unglaub** [shssoichiro/oxipng#100]
Hey,
first of all i want to thank you for oxipng. I use it as a binary but also as a library and i really love it. Reading the source helped me a lot in understanding how the PNG format actually works.

Now to my problem. The Zopfli algorithm does not work for me. The program just loops to infinity. I tryed a png file with 500kb and no matter what -o setting i use oxipng does never finish. I know that Zopfli algorithm is slower, but i let it run for 3 hours on my new AMD Ryzen CPU before i killed the executable. I asume it should not be that slow ;)

I add you the file i was using. Just in case.
![1](https://user-images.githubusercontent.com/734684/38170386-aab11b4e-3584-11e8-9c99-5ecee3f75b23.png)

I am on your latest release with OpenBSD.
Thanks and greetings
Leo

**Comment by leo-unglaub** [comment]
I did a rebuild with a new version of rustc itself. Now it seams to work fine. Maybe there was something wrong with my local rustc, but now it works fine. It takes around 2 minutes for an image. Thats still alot, but totally fine!

**Comment by shssoichiro** [comment]
I feel like I've encountered a similar issue as well when building a Rust nightly. Strange, but glad that it's fixed. 2 minute is a bit slow for a 150kb image compared to my benchmarks, but it could depend on the speed of the machine (I wouldn't expect a Ryzen to perform that much worse than an i7 though. Are you compiling with `--release`?)

**Comment by leo-unglaub** [comment]
I am sure my AMD Ryzen can outperform every current Intel CPU. I think the cause for the 2 minutes is my operating system. As awesome as OpenBSD is, its horribly slow in some cases :)
