### ISSUE TITLE
`-f 0,4,5` = invalid syntax?

### ISSUE THREAD

**Issue by magicgoose** [shssoichiro/oxipng#101]
`-f 0,5` option seems to be accepted just fine. As I understand, it means to try 0 and 5 filters. 
However, if I change it to `-f 0,4,5` (adding 4), I get:
`error: Invalid value for '--filters <filters>': Invalid option for filters`

```
$ oxipng --version
oxipng 1.0.4

$ rustc --version
rustc 1.26.1 (827013a31 2018-05-25)
```

Are there valid ways to let it try these 3 filters?

By the way, I might try to develop a PR to allow more than 2 values if you approve. (I think I found in the code why it allows only 2 values with a comma; but I'm not very experienced with Rust yet)

**Comment by shssoichiro** [comment]
Thanks for reporting this. I don't see any reason not to allow more than 2 values; it was probably an oversight when I originally coded it. I would be fine accepting a PR to fix this--otherwise, if you're unable to do so, I can create the bugfix.

**Comment by magicgoose** [comment]
I will try to do this. Should be easy enough.
