### ISSUE TITLE
An option to use zopfli but only once (for the final pass with probably-best filters/palette/etc.)

### ISSUE THREAD

**Issue by magicgoose** [shssoichiro/oxipng#106]
As we know Zopfli is very slow, so it's quite wasteful to run it several times.  
What I propose is a "fast zopfli" option which will make it work like this:
1) test various filters/palette/etc. combinations with a faster compression scheme (zlib-something)
2) pick the best filters/palette/etc. combination and use zopfli compression with them for the final result.  

I tested this approach on a collection of images (without modifying any code, just applying zopfli compression with `advdef` utility as a separate step), and it seems to give better compression/time tradeoff.

**Comment by shssoichiro** [comment]
Thanks! This sounds like a good idea.

**Comment by nosilver4u** [comment]
I would like to see something like this also, where one could run -o 3 to get the best zlib strategy, and then a single pass with zopfli to see if it can beat zlib. I've been running some tests to see if oxipng would work for us, and I was excited to perhaps ditch advpng for our workflow, but a handful of my sample images do better with zlib.
