### ISSUE TITLE
Distribute Linux and macOS binaries

### ISSUE THREAD

**Issue by Calinou** [shssoichiro/oxipng#134]
It would be helpful to have Linux and macOS binaries on the Releases page, so that users can get started with oxipng faster, especially on slower machines such as the Raspberry Pi. This would also make it possible to add oxipng to [Homebrew](https://brew.sh/) for easy installation on macOS.

I used [trust](https://github.com/japaric/trust) to cross-compile to various platforms/architectures in [one of my crates](https://github.com/Calinou/lagraph) and it worked well, so I would recommend it.

**Comment by jansol** [comment]
Homebrew is shipping oxipng already. Linux binaries are generally better left to distro package managers as well. OTOH a static musl binary could come in handy at times.

**Comment by TPS** [comment]
`OxiPNG` has been [added to the TUR](https://github.com/termux-user-repository/tur/pull/2134) yesterday for convenience & semi-official support! 🎉
