### ISSUE TITLE
cf-zlib is activating on i686 when it shouldn't be

### ISSUE THREAD

**Issue by shssoichiro** [shssoichiro/oxipng#137]
This is causing build failures. Does anyone actually use i686 anymore? I'm tempted to just disable the i686 builds. Although really, I should probably fix this.

**Comment by f2d** [comment]
I used an i686 server until only half a year ago, and I changed it only because of low total memory and my growing requirements. I was using using oxipng among several other utilities there.

I don't know much about widely spread hardware and setups, but there could still be some other cases.
