### ISSUE TITLE
Auto-install dependencies for compare script

### ISSUE THREAD

**Issue by shssoichiro** [shssoichiro/oxipng#139]
I was just trying to run the compare script, but didn't have `hyperfine` installed. Could this be installed automatically? Or added as a requirement in the docs? thanks.

The node_modules/stip-ansi causes a problem as well. Is there an npm install I'm missing? thanks

_Originally posted by @jamesstout in https://github.com/shssoichiro/oxipng/issues/81#issuecomment-422019746_

**Comment by andrews05** [comment]
The npm module is no longer required in v9.
We can't reasonably install hyperfine automatically as this is highly dependent on the platform. Note though that the compare script is more of an internal tool to add benchmarks to the Read Me, and isn't particularly useful for end users.
