### ISSUE TITLE
Fails on 2-bit greyscale images

### ISSUE THREAD

**Issue by jhaye** [shssoichiro/oxipng#140]
I'm currently trying to compress my archive of scanned documents from my studies.

First I converted all of the image files to 2-bit greyscale images with:
`convert in.jpeg -colorspace gray -depth 2 out.png`

Then I try to shave off some additional bytes with oxipng, however oxipng fails with:
```
Processing: 0021.png
    2548x3543 pixels, PNG format
    1x2 bits/pixel, Grayscale
    IDAT size = 201536 bytes
    File size = 201833 bytes
Reducing image to 1x1 bits/pixel, Grayscale
Trying: 8 combinations
Found better combination:
    zc = 9  zs = 1  f = 0        148458 bytes
    IDAT size = 148458 bytes (53078 bytes decrease)
    file size = 148634 bytes (53199 bytes = 26.36% decrease)
The resulting image is corrupted and will not be outputted.
This is a bug! Please report it at https://github.com/shssoichiro/oxipng/issues
```

I also tried this with other files and the result is the same.

**Comment by TPS** [comment]
@jhaye If possible, an example image would be helpful.  Especially, after `convert`, are the images actually B&W⁉️ 🤔

**Comment by jhaye** [comment]
@TPS I wanted to provide a sample file, but Github won't let me upload one.
So I have resized the image considerably and encoded it as base64, you can get it like this:

`echo iVBORw0KGgoAAAANSUhEUgAAAEwAAABqAgAAAAB5ufB9AAAABGdBTUEAALGPC/xhBQAAAAJiS0dEAAMzhHKIAAAACXBIWXMAAA+IAAAPiAEWyKWGAAAAB3RJTUUH4goCCxIC7U4+HQAAAE1JREFUSMdj+I8BrjJgiv0fhGL7idYLVvkeXd1rwnrfU+rm/VjE3lNg3qjYqBjZYvtJ1fueSDFy3Ac1Zz85ekfFqC/2fhC5ZVRsyIkBAO5i1J6eCpofAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDE4LTEwLTAyVDExOjE4OjAyKzAyOjAwjqsZjwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAxOC0xMC0wMlQxMToxODowMiswMjowMP/2oTMAAAAASUVORK5CYII= | base64 -d > file.png`

Oxipng fails on this file too, so I hope this helps.

**Comment by shssoichiro** [comment]
Thanks, I'll take a look at this!
