### ISSUE TITLE
Strange optimization regression

### ISSUE THREAD

**Issue by RazrFalcon** [shssoichiro/oxipng#142]
I have a file that was optimized 5 months ago and when I've tried to optimize the same file today it turned out to be much larger.

I've tried each oxipng version down to 1.0.0 and all of them produce the same results.

Here is the original image (5.9KiB):

![original](https://user-images.githubusercontent.com/725494/48348722-cfbdd500-e68a-11e8-86eb-75c2d5d38085.png)

Optimized today with `-o 6 -Z -s` via 2.1.5 (4.5KiB):

![test](https://user-images.githubusercontent.com/725494/48348771-ef54fd80-e68a-11e8-9213-fe0b53286184.png)

And the one that was diffidently optimized via oxipng 5 month ago with `-o 6 -Z -t 4`, but I don't understand why it's so small (1.8KiB):

![test-old](https://user-images.githubusercontent.com/725494/48348837-19a6bb00-e68b-11e8-9ee2-883bbec3ca36.png)

They all look identical for me.

**Comment by kornelski** [comment]
The files are different. The latest oxipng compresses the small one's IDAT to 1764 bytes. A bit larger than 1755 in the file, but not a major regression.

**Comment by RazrFalcon** [comment]
Maybe a bit, but how does it makes the second one 2x smaller?

**Comment by kornelski** [comment]
The difference is tiny, but PNG is lossless, so it'll spend as many bits as necessary to keep 100% of it:

![48348837-19a6bb00-e68b-11e8-9ee2-883bbec3ca36 png](https://user-images.githubusercontent.com/72159/51792562-b7018d80-21aa-11e9-9a73-4eec13ffc59c.png)
![Uploading 48348722-cfbdd500-e68a-11e8-86eb-75c2d5d38085.png.png…]()

**Comment by andrews05** [comment]
Closing as there doesn't appear to be an actual issue here.
