### ISSUE TITLE
Incorrect handling of 2x2 interlaced image

### ISSUE THREAD

**Issue by kornelski** [shssoichiro/oxipng#151]
This causes panic: ![s02i3p01](https://user-images.githubusercontent.com/72159/49287122-2ea98980-f494-11e8-830a-eee526e7b5a0.png)

> thread 'main' panicked at 'attempt to subtract with overflow', src/png/scan_lines.rs:160:9

**Comment by shssoichiro** [comment]
Sorry for the delay on getting to this. Do you have a sample image that produces this?

**Comment by kornelski** [comment]
I think it was one of images in the PNG test suite:

http://www.libpng.org/pub/png/pngsuite.html

**Comment by TPS** [comment]
For testing, try http://www.schaik.com/pngsuite2011/PngSuite-2017jul19.tgz?

**Comment by fhanau** [comment]
This should be fixed with #175 and #181, which address interlacing issues.

**Comment by fhanau** [comment]
@shssoichiro it was actually #175 and #182, but I think this issue can closed now.

**Comment by shssoichiro** [comment]
Thanks! Sorry, I've been trying to catch up on the open PR's, but day job + home life have kept me busy lately.

**Comment by fhanau** [comment]
No problem, that applies to my own side projects too.
