### ISSUE TITLE
A black image is bigger that a green one

### ISSUE THREAD

**Issue by RazrFalcon** [shssoichiro/oxipng#155]
Here are two images:

![a-flood-color-001](https://user-images.githubusercontent.com/725494/49644389-fddfcc00-fa20-11e8-8bba-c92c9744f34b.png)

645B

![a-flood-color-002](https://user-images.githubusercontent.com/725494/49644394-00dabc80-fa21-11e8-9186-595157f2cfdb.png)

1196B

So the black one is twice as big. I don't know how the PNG work internally, but it's strange.

- Command: `-o 6 -Z`
- Version: 2.1.8

**Comment by RazrFalcon** [comment]
Also, an image only with a frame is also 1181B:

![a-fill-037](https://user-images.githubusercontent.com/725494/49644499-413a3a80-fa21-11e8-81dc-119910a58f37.png)

**Comment by fhanau** [comment]
The green image is smaller because it uses a 4-bit palette. The black image and the one with just a frame have color type 16-bit grayscale+alpha and can't be reduced further since the images contain 16-bit alpha pixels, so this is not an oxipng issue.

**Comment by shssoichiro** [comment]
@fhanau thanks for investigating this. Sounds like this can be closed.
