### ISSUE TITLE
WebAssembly version?

### ISSUE THREAD

**Issue by tomByrer** [shssoichiro/oxipng#157]
Wondering if anyone has / is planning to do a [WebAssembly](https://rustwasm.github.io/book/) version for NodeJS/browser usage?

**Comment by tomByrer** [comment]
Thanks for your consideration!

**Comment by AielloChan** [comment]
WASM now will get this error, hope wasm support
![image](https://user-images.githubusercontent.com/7900765/60880368-21e4e380-a276-11e9-96ef-2dda1bf7bbb4.png)

**Comment by RReverser** [comment]
In case anyone wants to try it out, I've fixed the relevant issues in https://github.com/shssoichiro/oxipng/pull/194.
