### ISSUE TITLE
Corrupted output using large (24000x24000) grayscale image

### ISSUE THREAD

**Issue by potentcocktail** [shssoichiro/oxipng#167]
I'm trying to optimize a large (24000x24000) grayscale image.  I use oxipng all the time for images of this size, so I was surprised when I got the following output:

andy@sandy:~$ oxipng -s -Z --out output.png "f=000000 t=0.0.png"
Processing: f=000000 t=0.0.png
    24000x24000 pixels, PNG format
    1x8 bits/pixel, Grayscale
    IDAT size = 32341177 bytes
    File size = 32353257 bytes
Trying: 2 combinations
Found better combination:
    zc = 0  zs = 0  f = 5        14173342 bytes
    IDAT size = 14173342 bytes (18167835 bytes decrease)
    file size = 14173473 bytes (18179784 bytes = 56.19% decrease)
The resulting image is corrupted and will not be outputted.
This is a bug! Please report it at https://github.com/shssoichiro/oxipng/issues
The resulting image is corrupted

I also tried with -o 4 instead of Zopfli. Same result:

andy@sandy:~$ oxipng -o 4 -s --out output.png "f=000000 t=0.0.png"
Processing: f=000000 t=0.0.png
    24000x24000 pixels, PNG format
    1x8 bits/pixel, Grayscale
    IDAT size = 32341177 bytes
    File size = 32353257 bytes
Trying: 24 combinations
Found better combination:
    zc = 9  zs = 0  f = 1        15640968 bytes
    IDAT size = 15640968 bytes (16700209 bytes decrease)
    file size = 15641099 bytes (16712158 bytes = 51.66% decrease)
The resulting image is corrupted and will not be outputted.
This is a bug! Please report it at https://github.com/shssoichiro/oxipng/issues
The resulting image is corrupted

I can't attach the image here, so here's a Google Drive link to it: https://drive.google.com/open?id=1zcV6uZ3mRtlf9mzDtIamPM3glm59z4tP

Edit: I'm using oxipng version 2.2.0 on Debian Linux:
andy@sandy:~$ uname -a
Linux sandy 3.16.0-7-amd64 #1 SMP Debian 3.16.59-1 (2018-10-03) x86_64 GNU/Linux

**Comment by shssoichiro** [comment]
Thanks for reporting this! It might be related to #168. I'll leave both open until I can verify both are fixed.
