### ISSUE TITLE
9000x9000 PNG gets corrupted

### ISSUE THREAD

**Issue by joshua-stone** [shssoichiro/oxipng#168]
I tried compressing [a mosaic image of the moon found on Reddit](https://old.reddit.com/r/space/comments/arer0k/i_took_nearly_50000_images_of_the_night_sky_to/egmo9s8/), and this is what I got:
```
$ time oxipng -Z -o6 -i 0 Copy\ of\ updated\ mosaic.png --out moon.png
Processing: Copy of updated mosaic.png
    9000x9000 pixels, PNG format
    3x16 bits/pixel, RGB
    IDAT size = 304863576 bytes
    File size = 304863698 bytes
Trying: 6 combinations
Found better combination:
    zc = 0  zs = 0  f = 4        290407972 bytes
    IDAT size = 290407972 bytes (14455604 bytes decrease)
    file size = 290408094 bytes (14455604 bytes = 4.74% decrease)
The resulting image is corrupted and will not be outputted.
This is a bug! Please report it at https://github.com/shssoichiro/oxipng/issues
The resulting image is corrupted

real	20m33.361s
user	112m21.149s
sys	0m19.084s
```

Here's the latest direct download link to the PNG that's still up:

http://test.nyy.ca/mosaic.zip

**Comment by shssoichiro** [comment]
Thanks for reporting this! I'll get this fixed ASAP.

**Comment by shssoichiro** [comment]
Looks like this and #167 were fixed upstream in https://github.com/PistonDevelopers/image/pull/860. oxipng will temporarily use the fixed, unpublished version of the `image` crate to fix this issue.
