### ISSUE TITLE
Never uses more than 6 threads

### ISSUE THREAD

**Issue by Cygon** [shssoichiro/oxipng#169]
Oxipng only ever uses 18% of my CPU power, or about 6 threads.

My command line is:
```
        /opt/oxipng/target/release/oxipng \
                --opt 6 \
                --zw 32k \
                --zopfli \
                --threads 24 \
                *.png
```

I've tried with and without the `--threads 24` option, it doesn't seem to change anything. Are there only 6 parameter combinations at those settings, is it using a limited thread pool or misdetecting my cpu count (default is supposedly 1.5x cpu cores, so if it somehow couldn't detect and fell back to a fixed value of 4...)

This is on Gentoo Linux, Kernel 4.19.27, system with two Xeon E5-2680 CPUs.

**Comment by Calinou** [comment]
To make better use of multiple CPU threads, you can run oxipng in parallel on multiple images using the GNU `parallel` tool (or its [Rust reimplementation](https://github.com/mmstick/parallel)):

```bash
parallel oxipng -o6 --strip --zopfli ::: **/*.png
```

**Comment by shssoichiro** [comment]
Normally `-o 6` would have 180 combinations which would easily max out the thread pool. But zopfli is less configurable than zlib, which means the number of trials we can do when using zopfli is fewer--6, specifically.

The help page specifies that `--zopfli` "overrides zlib-specific options", but it may be worth updating that text to clarify what that means.

**Comment by TPS** [comment]
Perhaps _(optionally?)_ using a Zopfli _fork_ (e.g., https://github.com/MrKrzYch00/zopfli) would be helpful?

**Comment by TPS** [comment]
[Leanify _just_ got proper parallel processing support.](https://github.com/JayXon/Leanify/pull/67)  Is there anything _there_ that'd be useful _here_, particularly the use of [TaskFlow](https://github.com/taskflow/taskflow)?

**Comment by TPS** [comment]
Would [glommio](https://github.com/DataDog/glommio) be useful?

**Comment by TPS** [comment]
https://github.com/shssoichiro/oxipng/issues/517#issuecomment-1603348983:
> [S]ince #169 was opened we've added new filter types, so it will use up to 10 threads now at `-o 6`.

**Comment by ace-dent** [comment]
@Cygon @TPS - Is this still an issue? Should the docs be updated with a suggested maximum threads?

**Comment by andrews05** [comment]
I think we can close this. Parallel processing is also coming in the next release, so it will take full advantage of all available threads when running on many files.
