### ISSUE TITLE
Additional heuristic filter strategies 

### ISSUE THREAD

**Issue by fhanau** [shssoichiro/oxipng#183]
There are a number of different filter heuristics that perform better than the one used in libpng documented [here](http://bjoern.hoehrmann.de/pngwolf/).

I have implemented two additional strategies on the [better-filters](https://github.com/shssoichiro/oxipng/compare/master...fhanau:better-filters) branch. There are a number of caveats with these that need to be discussed, so I am opening this as an issue instead of a pull request.

- The bigrams strategy is more expensive than minsum (the current heuristic), but on average delivers better results than minsum. Trying both strategies yields the smallest size.
- The distinct bytes strategy rarely delivers the best result in my tests and on average performs worse than minsum, so it's questionable whether it is worth including.
- Enabling these strategies by default inevitably increases runtime, so I am not sure what the best way to integrate them is. As a possible solution, I have written some code that will add the option to use heuristics to choose the color type, zlib strategy and filter strategy at a smaller compression level to decrease the time spent deflating. I plan to open a seperate pull request for those changes.
- For more aggressive optimizations, there are some additional filter strategies based on the size of the deflated scanline or the shannon entropy as implemented in [zopflipng](https://github.com/lvandeve/lodepng/blob/f6155a4206046a31a9532d70caf517845af64c83/lodepng.cpp#L5002)
- I also added an experimental bias factor to the bigrams strategy, which slightly improves compression on average, but needs more work.

**Comment by TPS** [comment]
Do any of the implementation updates from https://github.com/jibsen/pngwolf-zopfli (the original's @ https://github.com/hoehrmann/pngwolf), especially re: multi-threading via OpenMP, have any additional significance to this?

**Comment by fhanau** [comment]
Oxipng already uses multithreading to determine the filter strategy and IIRC using the genetic algorithm to decide between different heuristics did not prove helpful in my tests. Since zlib is currently the only deflate library used, there is no need for a seperate estimator. Only the extra filter strategies might be useful for improving the compression ratio.
