### ISSUE TITLE
Looking for Collaborators

### ISSUE THREAD

**Issue by shssoichiro** [shssoichiro/oxipng#189]
Given that my free time is limited and split between many things, and that oxipng has grown quite popular, I'm looking for 1-2 volunteers to help maintain the repository--preferably individuals who have been involved in oxipng development. This would primarily involve triaging issues and reviewing PRs, and may also involve publishing releases.

**Comment by TPS** [comment]
@shssoichiro Given recent commit & PR history, I'd like to nominate @andrews05, @XhmikosR, & @AlexTMjugador, if they're willing.

**Comment by AlexTMjugador** [comment]
I'd be glad to help out with triaging and reviewing PRs! My free time is also limited though, so I wouldn't feel comfortable being alone in that position and I most likely won't be able to implement big features or changes, but I believw more eyes can only help in this situation.

**Comment by andrews05** [comment]
Yeah, I'd be happy to help out too. I think it would be good if @shssoichiro still had final approval on all PRs though.

**Comment by shssoichiro** [comment]
Thanks, I've sent the two of you invites as collaborators, this should give you permission to review MRs and update issues. I appreciate all the help!

**Comment by XhmikosR** [comment]
Hey, sorry for the late reply. Thanks for the offer, but I'm not familiar with Rust, so I'm not sure I can help.

Keep up the good work, I definitely appreciate a good image compressor!

**Comment by andrews05** [comment]
Great, shall we close this now? 😄

**Comment by shssoichiro** [comment]
Closing this out, thank you for the help @andrews05 and @AlexTMjugador !

**Comment by TPS** [comment]
@shssoichiro If you've similar thoughts as expressed in https://github.com/adamkewley/libdeflater/issues/48, perhaps my sol'n https://github.com/adamkewley/libdeflater/issues/48#issuecomment-2942775527 might be useful?  You've mostly already done it, in all but org.

**Comment by shssoichiro** [comment]
Yes, I think officially creating an org is a great idea. The only hard part is picking a name. 😂

**Comment by TPS** [comment]
@shssoichiro As you might've noticed, `libdeflater` just picked the same for the org name.  Is `oxipng` available for org?

**Comment by AlexTMjugador** [comment]
> Is `oxipng` available for org?

It should be, https://github.com/oxipng returns a 404 error. I've also chosen organization names to match their main project in the past, and I've seen others do the same when an organization grows out of a specific project.

Personally, given the current state of Oxipng and the short-term plans I can see for it, moving it to an organization likely wouldn't affect any day-to-day operations. That said, organizations do offer better tools for managing teams and related projects, which is always a positive when a community of maintainers is involved. So, I'm happy to go with whatever Josh thinks is best for the project.

**Comment by AlexTMjugador** [comment]
Now that @shssoichiro created an organization for Oxipng, I took the liberty to add a placeholder logo for it. Feel free to suggest a better one we have the right to use 😄

**Comment by andrews05** [comment]
@AlexTMjugador The placeholder should be fine for now. I'm not a graphic designer, but I asked ChatGPT for some ideas. These are obviously not usable as-is, but could be used as a starting point.

![Image](https://github.com/user-attachments/assets/bde9b574-5708-412e-865a-7e06bcbb14da) ![Image](https://github.com/user-attachments/assets/14470502-e31e-4620-a3b3-376f8677e0af) ![Image](https://github.com/user-attachments/assets/ac85022c-dc99-4197-89bf-e21227bd8ecf) ![Image](https://github.com/user-attachments/assets/4f364434-a2f9-4f5e-9b86-698bbdc1c00f)

(It decided an "ox" might look good)

**Comment by AlexTMjugador** [comment]
Funnily enough, I also asked ChatGPT for the the current placeholder logo... It was so generic looking that after some tweaks in GIMP from my part it ended up as a pretty decent placeholder graphic 😂

Your prompts clearly resulted in a more interesting look, however. Short of a more proper design, I prefer the top left logo more, as we can easily make it have a transparent background and is simple enough to look alright at most resolutions.

**Comment by ace-dent** [comment]
@AlexTMjugador -

> ... add a placeholder logo for it...

I actually adore how generic it is! Kind of a liminal aesthetic! 
+1

**Comment by TPS** [comment]
Perhaps if we get SVG/vector version(s) of logos (sacrilege for a PNG utility repo, I know!), perhaps we can manually tweak some suggestions to something a bit more suitable?

**Comment by shssoichiro** [comment]
Not gonna lie, I kinda love the ox. 😂

**Comment by TPS** [comment]
Will this do?

![image+bull2.svg.gz](https://github.com/user-attachments/files/20818469/image%2Bbull2.svg.gz)

**Comment by TPS** [comment]
<details>
<summary>
Will this do?
</summary>

![Image](https://github.com/user-attachments/assets/9b625a63-5fed-4d39-a234-6f4a43475417)

</details>

<details>
<summary>
Or how's this (via CrAIyon)?
</summary>

![Image](https://github.com/user-attachments/assets/5b8c2cce-a923-4b6b-be1d-b166b7a16521)

</details>

<details>
<summary>
I like this logo via Duck.AI.  What do you think?  Since it's SVG, it can be resized anyway 1 likes.
</summary>

![Duck.AI OxiPNG Logo SVG](https://github.com/user-attachments/assets/14a684fb-2945-48cc-a959-04cc127bd218)

</details>

**Comment by ace-dent** [comment]
Thanks @TPS. This is very subjective... but for me personally, a bull has no correlation with compression... 🤷🏼
I've grown to really like the current project logo.

Edit: reading back through, I see this is meant to be an 'Ox' !?... Not sure that's obvious. My mind links `oxipng` with `oxygen` - light as air, etc.

**Comment by TPS** [comment]
> Not gonna lie, I kinda love the ox. 😂

@ace-dent: @shssoichiro & the LLMs love the ox.  How could it be bad? 😜
> I've grown to really like the current project logo.

I'd like something more distinctive.  The current logo hints @ images, but nothing else really.  It's _not_ bad, but a bit `meh`.
