### ISSUE TITLE
Level 3 outperforms level 4

### ISSUE THREAD

**Issue by fhanau** [shssoichiro/oxipng#192]
When tested on a larger number of images, level 4 has a lower average compression ratio than level 3. This really shouldn't happen, but I am not quite sure why it does (perhaps something wrong with the evaluation code or alpha reduction itself). In general it might be a good idea to collect numbers on how each level performs to make it easy to compare performance and compression ratio numbers.

**Comment by TPS** [comment]
This is now obsolete since level 4 is now same as 3.
