### ISSUE TITLE
Make verbose mode configurable

### ISSUE THREAD

**Issue by antoni-alvarez** [shssoichiro/oxipng#196]
Oxipng its a great tool, but I think is too much verbose when processing image in bulk. Please make verbose mode configurable at different levels. IMHO the optimal level for verbose mode is like advpng:

Original size - Processed size - % reduction - filename

Example:
        1593        1505  94% image1.png
        1286        1243  96% image2.png
        1129        1129 100% image3.png (Bigger 1133)
        1253        1253 100% image4.png

**Comment by andrews05** [comment]
This has been greatly improved in the v9 release and should hopefully cover your use case.
