### ISSUE TITLE
Most benchmarks use obsolete APIs

### ISSUE THREAD

**Issue by RReverser** [shssoichiro/oxipng#197]
When trying to build benchmarks, there is lots of compilation errors due to the usage of obsolete or private APIs, which makes it hard to experiment with any potential performance improvements.

They should probably be fixed up and CI should always run `cargo +nightly build --all-targets` to make sure that entire codebase remains compilable after API changes.

**Comment by RReverser** [comment]
> They should probably be fixed up and CI should always run cargo +nightly build --all-targets to make sure that entire codebase remains compilable after API changes.

Might be still worth adding this as well.

**Comment by shssoichiro** [comment]
Already added. 🙂
