### ISSUE TITLE
Non-deterministic output

### ISSUE THREAD

**Issue by RReverser** [shssoichiro/oxipng#198]
Trying to run e.g.

```bash
cargo run -- -o 6 -P tests/files/grayscale_alpha_16_reduce_alpha_right.png --alpha
```

on current master (39ff7cfd5c8403af82df097f7a227ebac370254a) seems to produce non-deterministic results.

Sometimes I'm getting

```
Processing: tests/files/grayscale_alpha_16_reduce_alpha_right.png
    200x152 pixels, PNG format
    2x16 bits/pixel, GrayscaleAlpha
    IDAT size = 32322 bytes
    File size = 32400 bytes
Trying: 216 combinations
Found better combination:
    zc = 9  zs = 1  f = 5        20295 bytes
    IDAT size = 20295 bytes (12027 bytes decrease)
    file size = 20373 bytes (12027 bytes = 37.12% decrease)
Running in pretend mode, no output
```

and sometimes (more frequently) a worse result

```
Processing: tests/files/grayscale_alpha_16_reduce_alpha_right.png
    200x152 pixels, PNG format
    2x16 bits/pixel, GrayscaleAlpha
    IDAT size = 32322 bytes
    File size = 32400 bytes
Trying: 216 combinations
Found better combination:
    zc = 9  zs = 1  f = 5        20335 bytes
    IDAT size = 20335 bytes (11987 bytes decrease)
    file size = 20413 bytes (11987 bytes = 37.00% decrease)
Running in pretend mode, no output
```

Originally posted as comments on https://github.com/shssoichiro/oxipng/commit/239ca81db7b45b3ac731a8d8b2746e760500d0a9#commitcomment-37751319.

**Comment by RReverser** [comment]
Verbose logs don't reveal anything obvious - for same combinations the "good" result just always outputs better sizes than the "bad" result for same combinations.

**Comment by RReverser** [comment]
Can reproduce even with `-t 1` (single thread), so either that option is ignored somewhere, or at least it's not a thread race, which makes it even weirder...

**Comment by RReverser** [comment]
Looks like it's a result of different evaluation result "winning" in different cases due to different order.

**Comment by RReverser** [comment]
Looks like if I remove the "bias" code in the evaluator, then I consistently get the better results.

It seems to make sense, given that we always want to compare actual lengths independently from order, but maybe I don't understand the role of that code there in the first place?

**Comment by RReverser** [comment]
@kornelski Looks like you've introduced `bias` in https://github.com/shssoichiro/oxipng/commit/9af874d21be301a388678f8528590ad7aca9a568 - can you explain its role and whether it's still useful / necessary given the above?

**Comment by fhanau** [comment]
I've fixed previous issues with non-deterministic code (#173 #178), I'd assume it's either an issue with the bias code or uninitialized memory.
In my testing, the bias code had a negligible, but slightly negative impact on the average compression ratio, so I think it can be removed.

**Comment by kornelski** [comment]
Pixel formats are evaluated using fast compression, which is less smart than the final compression pass. That size should be considered a noisy estimation.

Some pixel formats/filters tend to compress much better than others, but I don't trust fast estimator to accurately see that. I've introduced bias to prevent them losing by accident only because fast compression estimate lost by a few bytes.

**Comment by RReverser** [comment]
@kornelski I see, that makes sense in general. I'm not sure I understand why such comparison turns out to be non-deterministic though? Shouldn't same combination of params always win evaluation?

**Comment by kornelski** [comment]
I've fumbled it by comparing size with bias to size without bias, which is order-dependent.

**Comment by RReverser** [comment]
So... is that a bug that we can fix or just an inherent property of such method of evaluation?

**Comment by kornelski** [comment]
The bias could work if it was made order-independent, but since it was a unscientific fudge factor, I'm OK removing it.
