### ISSUE TITLE
Add option and functionality to allow for lossy alpha reductions

### ISSUE THREAD

**Issue by CounterPillow** [shssoichiro/oxipng#23]
Several other PNG optimisers such as zopflipng have the option to perform "lossy" alpha optimisations. Pixels which are fully transparent may still have RGB data associated; the "lossy" part is to discard said RGB data (which means it's perceptually lossless). An advanced form of this is to set the fully transparent pixels to an RGB value that allows easier compression by the block filters and DEFLATE, depending on the visible pixel data in the image.

**Comment by shssoichiro** [comment]
Thanks for the suggestion! I can see the merit in this. I'm on the fence as to whether this should be an option or enabled by default.

It shouldn't be too difficult to implement the advanced form to play well with the block filters and DEFLATE. Something like:
Set RGB value to those of the previous pixel. If no previous pixel, set to the value of the pixel above. If this is the first pixel in the image, set to 0 0 0.
