### ISSUE TITLE
build failure with old rustc

### ISSUE THREAD

**Issue by keturn** [shssoichiro/oxipng#232]
This is not at all urgent, but maybe there's some minimum-compiler-version setting that could use updating?

```
error[E0599]: no method named `map_or` found for type `std::result::Result<&str, std::str::Utf8Error>` in the current scope
   --> oxipng-3.0.0/src/lib.rs:820:55
```

went away after I did `rustup update` and tried again. (from 1.40.0 to 1.43.1)

Cheers!

**Comment by shssoichiro** [comment]
On the readme, it is noted that the minimum supported Rust version is 1.41.0. Unfortunately there's no simple way to just set a "minimum rust version" flag, but I've seen this done with a custom build script. Making a clearer error message would be helpful, so that can be something to add.
