### ISSUE TITLE
Checksum for v3.0.0 source archive has changed

### ISSUE THREAD

**Issue by samford** [shssoichiro/oxipng#237]
I was recently updating the Rust formula in Homebrew and discovered that [the sha256 checksum for the oxipng v3.0.0 release source archive changed](https://github.com/Homebrew/homebrew-core/pull/55793#issuecomment-639491428) from the time it was originally posted and now.

We generally have to account for the change before we update the checksum in the formula (to help rule out undesirable changes). Is there any explanation for why the archive changed and what's different in the newer file?

**Comment by shssoichiro** [comment]
There were some issues with the deploy action that creates the release binaries. A few attempts at fixing this resulted in the binaries getting uploaded more than once. The binaries should have identical functionality, but may not be byte-identical due to multithreaded compilation.

**Comment by samford** [comment]
It's usually something like that but we always have to check. Thanks!
