### ISSUE TITLE
Should --strip really strip the gAMA chunk by default?

### ISSUE THREAD

**Issue by CounterPillow** [shssoichiro/oxipng#24]
Currently, `--strip` strips the gAMA chunk, which, while a small bit of metadata, significantly affects the way some applications display images (notably browsers).

Test image with arbitrarily added gAMA: 

![](https://fratti.ch/tmp/kde-logo-gamma.png)

Without gAMA:

![](https://fratti.ch/tmp/kde-logo-no-gamma.png)

People may be lead to perform `--strip` to get rid of things such as zTXT chunks, without knowing that gAMA is a thing. (Granted, many applications don't handle gAMA anyway, but browsers do.)

**Comment by shssoichiro** [comment]
Yes, I was concerned about this as well. I'm planning on improving the `--strip` option to better account for this. See #22.

(Closing this as duplicate)

**Comment by CounterPillow** [comment]
Oops, only saw that one just now, sorry!

**Comment by shssoichiro** [comment]
No worries. I did bump the priority of #22 because of this issue.
