### ISSUE TITLE
Don't overwrite the file when the size increases

### ISSUE THREAD

**Issue by nao20010128nao** [shssoichiro/oxipng#243]
Related to #195 , oxipng should not overwrite the file when the result is larger than original.     
optipng doesn't overwrite the file in this case by default.

**Comment by shssoichiro** [comment]
This should already be the default behavior. You can tell oxipng to overwrite always with the `--force` flag, but the default behavior is to only overwrite if either 1) the output would be smaller than the input or 2) interlacing is either added or removed.

Please let me know if you have an instance of this happening, and I can reopen the issue if that is the case.
