### ISSUE TITLE
Please support running in parallel across multiple files

### ISSUE THREAD

**Issue by joshtriplett** [shssoichiro/oxipng#275]
If I run `oxipng -Z *.png` on a directory full of PNG files, it runs 2 combinations at a time on one file at a time, using 100% of two CPUs and leaving all the others idle.

I'd love to have oxipng run on all the PNG files given to it in parallel, up to the limits of available CPUs. That would make it easier to run oxipng on a large number of images quickly.

**Comment by Mithgol** [comment]
Oxipng would then need some hotkeys to pause (and later to resume) such processing — the keys you'd press when you suddenly need some free CPU cores.

[Software flow control](https://en.wikipedia.org/wiki/Software_flow_control) of Ctrl+S and Ctrl+Q does not pause immediately (it just prevents new threads from running, but the threads already in progress may take many minutes to finish in Zopfli mode).

Oxipng that is not running in parallel across multiple files (i. e. is running in a simple `for` loop) can be somewhat “paused” by terminating the current instance of oxipng (by Ctrl+C) and can be later resumed by finally answering “No” to the operating system's question of whether the outer `for` loop should be broken:

![(screenshot)](https://user-images.githubusercontent.com/1088720/89332420-0841e580-d69c-11ea-85e9-d89c64196970.png)

Of course by such “pause” you'd lose the results of your current file's processing and would have to re-run oxipng on that file later or in a parallel window. But at least there's some way to free some CPU cores from oxipng when you need them.

But if there's no outer loop and oxipng loops itself in parallel across multiple files — well, then you won't Ctrl+C to terminate; you'd fear to lose all the progress and won't be able to resume. And thus such improved oxipng would likely need some pause/resume hotkeys of its own.

**Comment by joshtriplett** [comment]
On Tue, Aug 04, 2020 at 12:03:07PM -0700, Mithgol wrote:
> Oxipng would then need some hotkeys to pause (and later to resume) such processing — the keys you'd press when you suddenly need some free CPU cores.

That seems like an entirely unrelated feature request.

Also, you can hit Ctrl-Z (or send SIGSTOP) to suspend a process.

**Comment by shssoichiro** [comment]
I'm not sure if this is something that I'd like to add in the immediate future. Maybe down the road? The reason I say this is because you can already accomplish this using the [parallel tool](https://saveriomiroddi.github.io/Running-shell-commands-in-parallel-via-gnu-parallel/) on Mac/Linux or [this similar tool for Windows](https://github.com/shenwei356/rush).

**Comment by joshtriplett** [comment]
@shssoichiro There are a few reasons to integrate it into oxipng. oxipng itself runs multiple threads (to test multiple ways to shrink a file in parallel), so running multiple instances of oxipng can produce an unexpectedly large number of threads. If oxipng handles it itself, it can maintain a queue to keep all CPUs busy without overload.

**Comment by TPS** [comment]
> If oxipng handles it itself, it can maintain a queue to keep all CPUs busy without overload.

E.g., #169

**Comment by q3cpma** [comment]
It would be ridiculously bloated to reinvent xargs -P/parallel in all tools. If you want some kind of nested threading optimization, do like GNU make -l does: only spawn new threads if the load average is too high.

**Comment by joshtriplett** [comment]
I don't think all tools should reimplement parallelism, only tools that already have their own internal parallelism and naturally operate on multiple files. oxipng doesn't necessarily have to have the parallelism it already does, since that *could* be reimplemented outside of oxipng (generate temporary files and see which one is smallest), but there's value in the integration and simplicity.

**Comment by TPS** [comment]
[Myself from https://github.com/shssoichiro/oxipng/issues/169#issuecomment-799861460] 😊:
> [Leanify _just_ got proper parallel processing support.](https://github.com/JayXon/Leanify/pull/67)  Is there anything _there_ that'd be useful _here_, particularly the use of [TaskFlow](https://github.com/taskflow/taskflow)?
