### ISSUE TITLE
oxipng corrupts certain images

### ISSUE THREAD

**Issue by CounterPillow** [shssoichiro/oxipng#29]
I used the following script to run oxipng on a large number of PNG files from my mpv screenshot directory (~650 files), comparing the output of oxipng with the original file using graphicsmagick's compare command. The oxipng version used was 3f42eae01c1469dc88461acc9ad919e35f573d75.

```bash
#!/usr/bin/env bash
OXI=~/Projekte/oxipng/target/release/oxipng
NUM=0
if [ ! -d "/tmp/oxifaults" ]; then
    mkdir "/tmp/oxifaults"
fi
while IFS= read -rd '' f; do
    rm -f "/tmp/oxitest.png"
    $OXI -F --no-clobber --out "/tmp/oxitest.png" "$f" >> /dev/null 2>&1
    gm compare -maximum-error 0 -metric MSE "$f" "/tmp/oxitest.png" >> /dev/null 2>&1
    if [ $? -ne 0 ]; then
        cp "/tmp/oxitest.png" "/tmp/oxifaults/$NUM-oxi.png"
        echo "$f -> $NUM-oxi.png"
        ((NUM++))
    fi
done < <(find "$1" -type f -iname '*.png' -print0)
```

A number of images where the output did not correspond to the input were detected.

0. [Original](https://fratti.ch/oxicompare/0.png) -> [Oxipng](https://fratti.ch/oxicompare/0-oxi.png)
1. [Original](https://fratti.ch/oxicompare/1.png) -> [Oxipng](https://fratti.ch/oxicompare/1-oxi.png)
2. [Original](https://fratti.ch/oxicompare/2.png) -> [Oxipng](https://fratti.ch/oxicompare/2-oxi.png)
3. [Original](https://fratti.ch/oxicompare/3.png) -> [Oxipng](https://fratti.ch/oxicompare/3-oxi.png)
4. [Original](https://fratti.ch/oxicompare/4.png) -> [Oxipng](https://fratti.ch/oxicompare/4-oxi.png)
5. [Original](https://fratti.ch/oxicompare/5.png) -> [Oxipng](https://fratti.ch/oxicompare/5-oxi.png)
6. [Original](https://fratti.ch/oxicompare/6.png) -> [Oxipng](https://fratti.ch/oxicompare/6-oxi.png)
7. [Original](https://fratti.ch/oxicompare/7.png) -> [Oxipng](https://fratti.ch/oxicompare/7-oxi.png)
8. [Original](https://fratti.ch/oxicompare/8.png) -> [Oxipng](https://fratti.ch/oxicompare/8-oxi.png)
9. [Original](https://fratti.ch/oxicompare/9.png) -> [Oxipng](https://fratti.ch/oxicompare/9-oxi.png)

(For reasons beyond my comprehension, KonoSuba screenshots seemed to be more likely to get corrupted than others; I'm going to assume oxipng has bad taste in anime.)

As one can see, subtitles, for some reason, often trigger this.

rustc version is `rustc 1.9.0-nightly (998a6720b 2016-03-07)`.

**Comment by shssoichiro** [comment]
Can you test again against f1e6506? I modified much of the filtering code and can't reproduce the issue anymore (I was able to reproduce on 3f42eae).

**Comment by CounterPillow** [comment]
The images which resulted in corruption before no longer appear to get corrupted.
