### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by zetok** [shssoichiro/oxipng#32]
Oxipng aec8e412a3b86d545cc5ad89d2d0d2736d2058aa

![dat ram](https://cloud.githubusercontent.com/assets/3148759/13894476/ed291ea0-ed5f-11e5-98a5-e993773b73a1.png)

Used image: https://gist.github.com/zetok/1452501c644959325d45

pls fix?

**Comment by shssoichiro** [comment]
You're right, it looks like this is an issue when using high optimization levels (`-o 6`). oxipng is trying to spawn all the compression threads at once, and each thread uses memory. This isn't a problem with `-o 2` (8 threads), but `-o 6` spawns 648 threads at once.

I'll need to add a limit to the number of threads spawned at one time. Probably 1.5x the number of CPU cores.
