### ISSUE TITLE
Clarification needed on minimum supported version of Rust.

### ISSUE THREAD

**Issue by trumpet205** [shssoichiro/oxipng#333]
I'm trying to compile master branch of oxipng on Odroid N2. The board is running on Armbian Buster (a flavor of Debian Linux) with Rust version 1.41.1 (from official Debian repository).

I'm using the master branch instead of stable release 3.0.1 because the lack of #277 on 3.0.1. Yet it fails to compile,

```
Compiling cloudflare-zlib v0.2.5
error[E0658]: use of unstable library feature 'atomic_min_max': easier and faster min/max than writing manual CAS loop
  --> src/atomicmin.rs:31:18
   |
31 |         self.val.fetch_min(new_val, SeqCst);
   |                  ^^^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/48655

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `oxipng`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
It appears that this error is related to #328, which I'm guessing bumped the minimum supported version for Rust? Manually undo #328 on my end fixed the compilation error.

But README.md still says the minimum supported version for Rust is 1.41.0? Some clarification on this matter will be helpful.

**Comment by shssoichiro** [comment]
Sorry, that's an oversight on my end. The readme should have been updated along with the minimum version.
