### ISSUE TITLE
No binaries for 4.0.1 and later

### ISSUE THREAD

**Issue by swsnr** [shssoichiro/oxipng#363]
Looks like the deploy pipeline broke with 4.0.1 so this release and later have no binaries on Github releases anymore.  I'm using this binaries frequently, and would appreciate to have them back.

Looking at the actions tab it just seems to be the i686 Windows release; is that still needed?  Does anyone still use 32bit Windows systems?  I'm in no position to fix that, but if removing the i686 binary is an option I can make a PR.

**Comment by shssoichiro** [comment]
There have been users who have requested the i686 binaries, so I'd like to fix those. However, I don't have a Windows machine set up to mess around with it. It's failing on a linker step and giving a very unhelpful error message (i.e. _something_ is broken with libdeflate). So I will temporarily disable i686 builds until a proper fix can be found.

**Comment by lunaryorn** [comment]
Thanks 🙏 I'm sorry that I can't help with Windows builds 😔

**Comment by TPS** [comment]
Is this still a problem?

**Comment by swsnr** [comment]
Not for me, because the binaries I care for are long back, but i686 is still not back, and presumably that's why this issue is still open.

As far as I'm concerned it can be closed though.

**Comment by XhmikosR** [comment]
@andrews05 this can be closed now along with #533 :)

**Comment by AlexTMjugador** [comment]
Yeah, this can be closed now, thanks for the reminder! CI workflows generate all desired binaries now.
