### ISSUE TITLE
Windows: Cannot specify infile in double quotes

### ISSUE THREAD

**Issue by Vasilich** [shssoichiro/oxipng#373]
When trying to specify files for optimization in double quotes (e.g. when path to file(s) contain spaces),
`oxipng -o max "folder with spaces\*.png"`
 then oxipng throws error "Failed to open file for reading".
Double quotes work though when used in option
`--dir "folder name with spaces\and subfolder"`
Is there a chance for this to be fixed?
Thanks in advance

**Comment by GeniusBroccoli** [comment]
same here

**Comment by TPS** [comment]
> Update. Do it :call_me_hand:
> This [thread](https://stackoverflow.com/questions/180741/how-to-do-something-to-each-file-in-a-directory-with-a-batch-script) was helpful.
> ```
> @echo off
> pushd %~dp0
> for /f tokens^=* %%i in ('where "%~1":*.png') do (
> 	oxipng -s --dir "%~1" "%%~dpnxi"
> 	echo.
> 	)
> pause
> ```

@Vasilich Does this solve for you?  If so, limitation of Windows batch file & not OxiPNG, & so issue should be closed.  🙇🏾‍♂️

**Comment by GeniusBroccoli** [comment]
> > Update. Do it call_me_hand
> > This [thread](https://stackoverflow.com/questions/180741/how-to-do-something-to-each-file-in-a-directory-with-a-batch-script) was helpful.
> > ```
> > @echo off
> > pushd %~dp0
> > for /f tokens^=* %%i in ('where "%~1":*.png') do (
> > 	oxipng -s --dir "%~1" "%%~dpnxi"
> > 	echo.
> > 	)
> > pause
> > ```
> 
> @Vasilich Does this solve for you? If so, limitation of Windows batch file & not OxiPNG, & so issue should be closed. 🙇🏾‍♂️

The idea of the last script is that it collects all the files in the directory and runs a new instance of OxiPNG for each one, substituting the full path to the file.

I hope that OxiPNG will have a built-in batch processing of files from directory, i.e. when calling `oxipng -s "%~1\*.png"` the program will parse the directory itself and perform optimization for each file without restarting.

I found a [similar problem](https://github.com/shssoichiro/oxipng/issues/90) among those solved. Maybe the current problem is a special case of this solved problem.

**Comment by Vasilich** [comment]
> @Vasilich Does this solve for you? If so, limitation of Windows batch file & not OxiPNG, & so issue should be closed. 🙇🏾‍♂️
No, it doesn't solve this problem, it just workarounds it.
I made similar workaround 2 years ago, but wanted it to be fixed for OxiPng. See my 1st post- it is not Windows problem - other argument works perfectly with quotes on Windows.
BTW, how should i specify file mask with path containing spaces in Linux?
