### ISSUE TITLE
Shortest path to using this as an external library?

### ISSUE THREAD

**Issue by tobz** [shssoichiro/oxipng#38]
Heyo!

Firstly, thanks for providing a competitor to OptiPNG! And written in a safer language, no less. :D

I've been working on a side project for doing behind-the-scenes compression/optimization of images being uploaded to a front-end service, and really wanted to write it in Rust.  Looking for image optimization libraries in Rust, your project came up.. but alas, it's not a library. :(

Is there a short path between what you have right now and me being able to use it as a library?

**Comment by shssoichiro** [comment]
Hey, welcome! Glad to see support for the project!

Although there are still things I want to do to make the library portion more user-friendly, you can link in the crate as a library. If you add oxipng as a dependency in your Cargo.toml, then `extern crate oxipng`, you should have access to all of the library functions documented [here](https://shssoichiro.github.io/oxipng/doc/oxipng/). The simplest method of usage involves creating an [Options struct](https://shssoichiro.github.io/oxipng/doc/oxipng/struct.Options.html) and passing it, along with an input filename, into the [optimize function](https://shssoichiro.github.io/oxipng/doc/oxipng/fn.optimize.html).

I also need to update the Readme to link to the docs. I just realized the only link is on the crates.io page.

**Comment by tobz** [comment]
Since I'm admittedly very unaware of the options for multithreading in Rust, does oxipng apply any opinions about how its multithreaded ops are happening?

Not that I'm scared of oxipng spinning up its own threads behind-the-scenes so much, but, just curious.

**Comment by shssoichiro** [comment]
Currently oxipng uses threads equal to 1.5x the number of CPU cores. There are no options at the moment for configuring this, although it would be nice to add that option in the future.

**Comment by tobz** [comment]
Noice.  Yeah, if someone wanted to have it operating out of a general CPU-bound thread pool or something, that would be useful.  I certainly don't need that right now, though, so not a biggie.

Alright, cool.  Thanks for the details! 👍
