### ISSUE TITLE
macOS Universal 2 binary for Apple silicon support? 

### ISSUE THREAD

**Issue by andrewcrook** [shssoichiro/oxipng#383]
Please consider this feature request of adding a universal 2 binary with both Intel and Apple Silicon support or a separate Apple Silicon package to the releases.

**Comment by z3cko** [comment]
Why is this ticket open? Would people not usually build the binaries with cargo anyways?

**Comment by ace-dent** [comment]
@AlexTMjugador is this now fixed with latest workflows?

**Comment by AlexTMjugador** [comment]
The latest workflows don't build universal macOS binaries, but they build macOS binaries for both x64 and AArch64 macOS devices and it's easy to pick the right one for your needs. So yeah, I consider this issue resolved! :tada:
