### ISSUE TITLE
Efficient Compression Tool

### ISSUE THREAD

**Issue by andrews05** [shssoichiro/oxipng#399]
Just wondering if you're aware of [ECT](https://github.com/fhanau/Efficient-Compression-Tool). It's the best performing png compressor I know of - I believe it's based on a highly optimised version of zopfli. Thought maybe oxipng could learn some tips from it...

**Comment by javiergutierrezchamorro** [comment]
> Just wondering if you're aware of [ECT](https://github.com/fhanau/Efficient-Compression-Tool). It's the best performing png compressor I know of - I believe it's based on a highly optimised version of zopfli. Thought maybe oxipng could learn some tips from it...

I am familiar with it. In fact I am using it in my FileOptimizer.
Maybe you can take a look to Leanify and PINGO too.

**Comment by ace-dent** [comment]
Hi @andrews05 - sorry to post on a closed issue...
Were the strategies from ECT studied and copied? Source [here](https://github.com/fhanau/Efficient-Compression-Tool/blob/master/src/zopflipng.cpp).

**Comment by andrews05** [comment]
@ace-dent Oof, this was before I knew anything about anything 🤣

ECT's strength is in its *fast* zopfli-derived compression engine. There's nothing oxipng itself can do with this, though it's possible some of the speed improvements could be incorporated into zopfli-rs.

I don't think there's anything to be gained from studying its reductions. I believe it does have some sort of genetic algorithm for filtering (similar to pngwolf?), but that's one of those "take all day to save a few bytes" kind of things.

**Comment by AlexTMjugador** [comment]
> There's nothing oxipng itself can do with this, though it's possible some of the speed improvements could be incorporated into zopfli-rs.

Yes, I think so too, although in some cases ECT did changes that affect output. Ideally, I would like `zopfli-rs` to incorporate both kinds of improvements, and offer a feature to opt-in to patches that may change the output of the original Zopfli algorithm.
