### ISSUE TITLE
Implement preserve `-p` option

### ISSUE THREAD

**Issue by shssoichiro** [shssoichiro/oxipng#4]
Oxipng has a command-line option to preserve original file attributes. This needs to be implemented, with at least one test case.

**Comment by f2d** [comment]
Is there a way to preserve the file modification date if the file was not changed?

**Comment by shssoichiro** [comment]
Oxipng shouldn't be changing the modification date if the file hasn't changed, because it doesn't write an output file if there's no improvement. At most, it would update the access date. However, I will investigate and see if there may be a reason this is happening.

**Comment by f2d** [comment]
I confirmed that it does not change modification date unless "-i 0" is specified. With any "-i" value it rewrites the file whether anything really changed or not.
