### ISSUE TITLE
Leanify tool provides better lossless compression than Oxipng.

### ISSUE THREAD

**Issue by RDKRACZ** [shssoichiro/oxipng#418]
https://github.com/JayXon/Leanify build from the source.
`leanify -p` vs `oxipng -arvZ -o max --strip all --fix`. Not all images were better compressed after using leanify on them, but overall results were better than Oxipng ones.

Assets in this repository were used for this test https://github.com/Waoweens/WaoTweaks.

**Comment by toscompliantname** [comment]
>Assets in this repository were used for this test https://github.com/Waoweens/WaoTweaks.



> remove unnecessary item
> 5bdad11
> 22 days ago

nigguh

**Comment by andrews05** [comment]
This should be resolved by #499, which will avoid changing RGBA to indexed in very tiny images like these. Note some of the images here are currently indexed and oxipng will not attempt to convert indexed to RGBA (which might be smaller), so it still isn't optimal but it does give a better overall result than leanify.

I did notice some of the images have some very faint partial transparency in them, which may be unintended. If you were to clean these up it should help improve compression, e.g. by allowing conversion to RGB+trns which might be smaller than RGBA.

**Comment by TPS** [comment]
> This should be resolved by #499

& further improved by #502.  Thanks, @andrews05! 🙇🏾‍♂️

**Comment by andrews05** [comment]
@TPS & further improved again 😄
