### ISSUE TITLE
Implement --terse CLI flag

### ISSUE THREAD

**Issue by folknor** [shssoichiro/oxipng#419]
Hi,

Currently, oxipng supports two relevant flags; `-v` for verbose, which as far as I can tell is only useful for debugging of oxipng itself, and `-q` for quiet mode, which completely suppresses any output. 

Here's an example with the default output:
```
$ oxipng oxipng --dir dist/www -p -s -a -D dist/www/*.png
Processing: dist/www/flagg.0f2b78c7.png
    1200x872 pixels, PNG format
    8 bits/pixel, 62 colors in palette
    IDAT size = 3358 bytes
    File size = 3840 bytes
Reducing image to 8 bits/pixel, 36 colors in palette
Trying: 2 combinations
Found better combination:
    zc = 0  zs = 0  f = 5        3067 bytes
    IDAT size = 3067 bytes (291 bytes decrease)
    file size = 3317 bytes (523 bytes = 13.62% decrease)
Output: dist/www/flagg.0f2b78c7.png
```

I think this is exceptionally verbose for something that is part of a build chain.

An option like `--terse` (or something else equivalent) to produce output like for example

```
$ oxipng ...
dist/www/flagg.0f2b78c7.png 13.62%
```

Which would be enough for me.

Or perhaps

```
$ oxipng ...
dist/www/flagg.0f2b78c7.png dist/www/flagg.0f2b78c7.png 3840|3317|13.62%
```
(src dest origsize compressed %)
Or some other way that makes it easy to parse programmatically (perhaps \t separators).

Thank you for an awesome tool, and thank you for reading my ticket!

**Comment by TPS** [comment]
How about #489 as a solution for this?

**Comment by folknor** [comment]
Perhaps. The pull request doesn't show an example of how the output looks with or without.

**Comment by TPS** [comment]
#488 gives more info, but reading #489's diff, it looks like it'd make the `info` level very similar to above.

**Comment by chrispy-snps** [comment]
I would also find this useful, for the same reasons. We process hundreds of images per document, and a summary of one line per image would be perfect.
