### ISSUE TITLE
Attempt to recompress iCCP, zTXt, and iTXt

### ISSUE THREAD

**Issue by gsnedders** [shssoichiro/oxipng#432]
These are all also deflated chunks, and as such it's probably worthwhile trying to recompress these with whatever compressor is in use.

**Comment by TPS** [comment]
Perhaps also judicious conversion of `tEXt`→`iTXt`→`zTXt` _before_ recompression to minimize input text representation?

Of course, that's assuming any of these chunks need to stay @ all.

**Comment by gsnedders** [comment]
The motivating thing here was iCCP, given that is preserved by `--strip safe`, with its implications on rendering. But by the point I filed the issue, it seemed like I may as well include all other compressed chunks given once you've done one, you may as well do them all.

**Comment by andrews05** [comment]
iCCP recompression has been added now. The best way to minimise text chunks is with `--strip` 😅
