### ISSUE TITLE
FUCK YOUR SHITTY RUST LANGUAGE

### ISSUE THREAD

**Issue by blattersturm** [shssoichiro/oxipng#433]
I was confused as to why my server running Discourse had all its CPU power be taken by some 'oxipng' program and wondered if someone typo'd 'optipng' but instead it turns out you're just another bucnh of rewrite-it-in-Rust retards.

FUCK.
RUST.

SERIOUSLY.

also fuck all the 'oxide' puns you moronic tardfucks are using and pushing on everyone.

**Comment by shssoichiro** [comment]
Thank you for bringing this to my attention. Your comment is very helpful, because it tells me that the sum of your brain cells is an imaginary number. I hope you enjoy being permanently banned from this repository and possibly all of Github. Good day.
