### ISSUE TITLE
Try to compress better than `pngcrush`

### ISSUE THREAD

**Issue by txtsd** [shssoichiro/oxipng#444]
Currently `pngcrush` at max settings always compresses a little more than `oxipng` at max settings.

Source used is `“Cosmic Cliffs” in the Carina Nebula (NIRCam and MIRI Composite Image)` from [webbtelescope.org](https://webbtelescope.org/contents/media/images/2022/031/01G780WF1VRADDSD5MDNDRKAGY).

```
λ wget "https://stsci-opo.org/STScI-01G8GYD8B1H306SSPR4MY6NGN0.png"
--2022-07-23 12:53:58--  https://stsci-opo.org/STScI-01G8GYD8B1H306SSPR4MY6NGN0.png
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving stsci-opo.org (stsci-opo.org)... 65.9.95.4, 65.9.95.10, 65.9.95.43, ...
Connecting to stsci-opo.org (stsci-opo.org)|65.9.95.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 50166110 (48M) [image/png]
Saving to: ‘STScI-01G8GYD8B1H306SSPR4MY6NGN0.png’

STScI-01G8GYD8B1H306SSPR4MY6NGN0.png            100%[======================================================================================================>]  47.84M  5.78MB/s    in 8.0s    

2022-07-23 12:54:08 (5.96 MB/s) - ‘STScI-01G8GYD8B1H306SSPR4MY6NGN0.png’ saved [50166110/50166110]
```

```
λ pngcrush -brute -rem alla -rem allb -rem text -reduce -check STScI-01G8GYD8B1H306SSPR4MY6NGN0.png pngcrush.png
  Recompressing IDAT chunks in STScI-01G8GYD8B1H306SSPR4MY6NGN0.png to pngcrush.png
   Total length of data found in critical chunks            =  50145112
pngcrush: iCCP: known incorrect sRGB profile
   Best pngcrush method        =  16 (ws 15 fm 5 zl 2 zs 2) =  45336617
CPU time decode 101.124237, encode 2127.660889, other 0.256804, total 2229.506836 sec
```

```
λ oxipng --opt max --strip all --alpha --interlace 0 --threads 8 --out oxipng.png STScI-01G8GYD8B1H306SSPR4MY6NGN0.png
Processing: STScI-01G8GYD8B1H306SSPR4MY6NGN0.png
    11264x3904 pixels, PNG format
    3x8 bits/pixel, RGB
    IDAT size = 50144491 bytes
    File size = 50166110 bytes
Trying: 216 combinations
Found better combination:
    zc = 1  zs = 2  f = 5        45398613 bytes
    IDAT size = 45398613 bytes (4745878 bytes decrease)
    file size = 45398670 bytes (4767440 bytes = 9.50% decrease)
Output: oxipng.png
```

```
λ ls -l *.png
-rw-r--r-- 1 txtsd users 45398670 Jul 23 12:59 oxipng.png
-rw-r--r-- 1 txtsd users 45336617 Jul 23 13:35 pngcrush.png
-rw-r--r-- 1 txtsd users 50166110 Jul 21 23:25 STScI-01G8GYD8B1H306SSPR4MY6NGN0.png
```

**Comment by TPS** [comment]
Using many tools can approach state-of-the-art.  It'd be instructive to try [FileOptimizer](https://github.com/shssoichiro/oxipng/issues/326#issuecomment-711372708) any way you can — it's the best I've found in the last decade or so, & almost certainly can do even better.

**Comment by txtsd** [comment]
Thanks, but it's windows-only. I'm a Linux user.

I'm just trying to remove `pngcrush` from my screenshot flow. If `oxipng` can achieve match or outcrush `pngcrush`, my screenshot flow will take a lot less time and CPU.

**Comment by TPS** [comment]
Optimum PNG compression is _always_ time-consuming.  If you're optimizing filesize for web use, maybe consider .WebP?

**Comment by TPS** [comment]
> Thanks, but it's windows-only. I'm a Linux user.

Also, [FO runs fine on ReactOS](https://nikkhokkho.sourceforge.io/images/fileoptimizer_reactos.png), which, in turn, [runs well on Linux via VirtualBox 5](https://reactos.org/wiki/VirtualBox).

**Comment by 8573** [comment]
> [FO runs fine on ReactOS](https://nikkhokkho.sourceforge.io/images/fileoptimizer_reactos.png), which, in turn, [runs well on Linux via VirtualBox 5](https://reactos.org/wiki/VirtualBox).

One also can look at File Optimizer's source code as linked from <https://github.com/shssoichiro/oxipng/issues/440#issuecomment-1140448591>.  It looks to me like a big shell script that happens to be written in C++: it works by running other programs on the file to be optimized.  One could find the part of the linked [`cppMain.cpp`](https://sourceforge.net/p/nikkhokkho/code/HEAD/tree/trunk/FileOptimizer/Source/cppMain.cpp) that deals with PNG files and then run the commands that it would run (maybe as a shell script, so that it's easy to do this again).  To me, this seems an easier and lighter-weight solution than setting up a virtual machine to run File Optimizer.

**Comment by TPS** [comment]
> To me, this seems an easier and lighter-weight solution than setting up a virtual machine to run File Optimizer.

This would be true if*f* many of the programs run weren't Windows-only binaries themselves.  [In simpler cases](https://github.com/shssoichiro/oxipng/issues/440), that's actually quite doable, but the PNG toolchain is _the_ most complex & has many such components.

**Comment by C0rn3j** [comment]
Running through already-max-optimized PNGs that were optimized with 6.0.1 with the new 7.0.0, I am seeing additional 2% to 28% decrease.

Unfortunately, retesting against your example, I get worse results.
```
% oxipng --opt max --strip all --alpha --interlace 0 --threads 8 --out oxipng.png STScI-01G8GYD8B1H306SSPR4MY6NGN0.png
Processing: STScI-01G8GYD8B1H306SSPR4MY6NGN0.png
    11264x3904 pixels, PNG format
    3x8 bits/pixel, RGB
    IDAT size = 50144491 bytes
    File size = 50166110 bytes
Trying: 10 filters
Found better combination:
    zc = 12  f = BigEnt    48290674 bytes
    IDAT size = 48290674 bytes (1853817 bytes decrease)
    file size = 48290731 bytes (1875379 bytes = 3.74% decrease)
Output: oxipng.png
```

Rerunning the 6.0.1 output against 7.0.0 provides zero new filesavings.
```
45398670 Dec  9 11:05 oxipng5.0.1.png
45398670 Dec  9 11:03 oxipng6.0.1.png
48290731 Dec  9 10:58 oxipng7.0.0.png
```

**Comment by TPS** [comment]
> Rerunning the 6.0.1 output against 7.0.0 provides zero new filesavings.

Maybe try again w/ _original_ input (to avoid local minima) &/or against recent v8.𝑥, while tweaking options further?  (This is mostly why I tend to shun PNG altogether nowadays in favor of something more modern, or fire up FO if it's something serious _**&**_ unavoidable.)

**Comment by Oondanomala** [comment]
Its a libdeflate problem, see https://github.com/ebiggers/libdeflate/issues/241

**Comment by ebiggers** [comment]
The master branch of libdeflate now compresses the IDAT of `STScI-01G8GYD8B1H306SSPR4MY6NGN0.png` to 45,281,576 bytes at level 12.

**Comment by TPS** [comment]
@shssoichiro Is there an ETA for when this updated library will be available in an OxizPNG release?

**Comment by ebiggers** [comment]
The improvements were released in libdeflate v1.17.  This project uses the Rust bindings https://github.com/adamkewley/libdeflater, so I guess you'll need to first get libdeflater to update libdeflate, then update libdeflater in this project.

**Comment by TPS** [comment]
`libdeflater` has just been updated to `libdeflate` v0.17.

@shssoichiro Is there an ETA for when this updated library will be available in an OxiPNG release?

**Comment by XhmikosR** [comment]
@shssoichiro friendly ping to update to the latest libdeflater :)

**Comment by parasew** [comment]
Hi all! I have provided a [patch](https://github.com/shssoichiro/oxipng/pull/495) with updated Cargo.toml, where libdeflater and Zopfli are updated. Here is the [gist for the test](https://gist.github.com/parasew/8a4fc4bd9253b7270d908e0a23a75d7e), and you can see that libdeflater 0.13.0 makes a huge difference. 

- oxipng -o6 yields 48290731 (0.11.0) / 45277379 (0.13.0)
- oxipng --zc 12 -o max 48290731 (0.11.0) / 45277379 (0.13.0)

All tests have been made the same file the OP was mentioning. [gist for the test](https://gist.github.com/parasew/8a4fc4bd9253b7270d908e0a23a75d7e)

**Comment by txtsd** [comment]
This is great! Thanks for y'all's help! I'll close this when it lands in a release.

**Comment by andrews05** [comment]
This has landed in #525.

**Comment by TPS** [comment]
> This has landed in #525.

Still hoping for a full release & associated binaries.

**Comment by XhmikosR** [comment]
Alternatively, one could modify the GitHub Actions to create and upload the binaries for each workflow run.

**Comment by TPS** [comment]
> Alternatively, one could modify the GitHub Actions to create and upload the binaries for each workflow run.

A PR for this, if possible? 🙇🏾‍♂️

**Comment by andrews05** [comment]
Now released in v9.
