### ISSUE TITLE
Zopfli compression in 6.0.0 results in a corrupted image in some cases

### ISSUE THREAD

**Issue by bgunnink** [shssoichiro/oxipng#449]
Using the newly-released 6.0.0 version on Windows 11 (64-bit) on the attached PNG results in the following:

`> oxipng -Z -o max cover.png`

```powershell
Processing: cover.png
    2981x2981 pixels, PNG format
    3x8 bits/pixel, RGB
    IDAT size = 6087921 bytes
    File size = 6088031 bytes
Trying: 6 combinations
Found better combination:
    zc = 0  zs = 0  f = 4        5897004 bytes
    IDAT size = 5897004 bytes (190917 bytes decrease)
    file size = 5897114 bytes (190917 bytes = 3.14% decrease)
The resulting image is corrupted and will not be outputted.
This is a bug! Please report it at https://github.com/shssoichiro/oxipng/issues
The resulting image is corrupted
```

As per instructions, here I am. 

The problematic image is available at https://user-images.githubusercontent.com/1986890/188520158-84a1a201-a63f-4884-b880-19980932551b.png

FWIW, I had just successfully compressed this image (same command) with `oxipng` 5.0.1 a few days ago.  

The `-o max` flag doesn't make a difference, either (same error), but I don't get the error in normal mode (it can't achieve better compression and doesn't even try, I guess).

**Comment by Maingron** [comment]
Noticed the same on Windows 10. Think this only applies to high-resolution images.

**Comment by AlexTMjugador** [comment]
I'm sorry about the issue. It's caused due to the `zopfli` version bump to 0.7, which contains a regression that is generating corrupt streams. I'll try to dig further in it.

**Comment by TPS** [comment]
Is there an issue filed upstream w/ `zopfli` itself?

**Comment by Maingron** [comment]
For your testing, here are some more images that failed on me. Weirdly it's not applying to all image of the same source.  
[Failing images for testing (issue 449).zip](https://github.com/shssoichiro/oxipng/files/9501407/Failing.images.for.testing.issue.449.zip)

**Comment by AlexTMjugador** [comment]
> Is there an issue filed upstream w/ `zopfli` itself?

No, there isn't, but that paperwork is not necessary because I'm a maintainer of that library, and I've just pushed a change that I believe will fix this issue: https://github.com/zopfli-rs/zopfli/commit/fcfb76c20801c5edd11cd1dd9b0a387c3e4e46df.

I'll test the fix with OxiPNG for a bit to confirm that the attached images are working fine now.

**Comment by Maingron** [comment]
If you provide a compiled version, I can run tests too. I got the error on quite many images.

**Comment by AlexTMjugador** [comment]
This is a Windows build of the changes I'm testing. I've cross-compiled from my Linux workstation and it seems to work well enough to show usage help under Wine: [oxipng.zip](https://github.com/shssoichiro/oxipng/files/9504941/oxipng.zip)

**Comment by Maingron** [comment]
@AlexTMjugador didn't get any errors so far. Also tried a 5760x2160 image, although I don't know if that one would have thrown an error.

**Comment by AlexTMjugador** [comment]
Thank you all for your input :smile:

I've just submitted a PR that should fix the issue.
