### ISSUE TITLE
Oxipng produces corrupted paletted images

### ISSUE THREAD

**Issue by DangerPie** [shssoichiro/oxipng#459]
Pngcheck says "bKGD index (61) falls outside PLTE (61)"
[wrong_bKGD_index.zip](https://github.com/shssoichiro/oxipng/files/9893334/wrong_bKGD_index.zip)

**Comment by andrews05** [comment]
Just FYI, I've been looking into this as it came up during some experiments I was doing. The bKGD colour can get dropped from the palette if it isn't used in the idat. I hope to get a PR up to fix this sometime, but it may be a little more involved than it seems...

**Comment by DangerPie** [comment]
IrfanView refuses to show that image.
