### ISSUE TITLE
How to force 8-bit depth quantization

### ISSUE THREAD

**Issue by oovm** [shssoichiro/oxipng#465]
I have a png image with 24 bit depth and I want to force 8 bit quantization, how to do it?

I tried `bit_depth_reduction`, but it didn't work.

```rust
    let opts = Options {
        bit_depth_reduction: true,
        ..Options::default()
    };
```

**Comment by andrews05** [comment]
oxipng doesn't do quantisation, it only reduces bit depth when it is possible to do so losslessly. You'll need a different tool such as [pngquant](https://github.com/kornelski/pngquant).

**Comment by oovm** [comment]
Oh thanks, i didn't realize that
