### ISSUE TITLE
Release notes missing in 7.0 GH release

### ISSUE THREAD

**Issue by txtsd** [shssoichiro/oxipng#471]
[CHANGELOG](https://github.com/shssoichiro/oxipng/blob/v7.0.0/CHANGELOG.md) has release notes, but the [GH Release](https://github.com/shssoichiro/oxipng/releases/tag/v7.0.0) is missing them.

**Comment by VadimMuhtarov** [comment]
Also what options for libdeflate compression?

**Comment by Maingron** [comment]
That

**Comment by shssoichiro** [comment]
I definitely need to get around to updating the README, the instructions there are definitely out of date... I'll make a separate issue for that, this one is fixed. :+1:
