### ISSUE TITLE
Resulting image is corrupted with oxipng 6.0.1 and 7.0.0 but not 5.0.1

### ISSUE THREAD

**Issue by C0rn3j** [shssoichiro/oxipng#473]
Curiously, .7z compresses this very good.
[Oxiorig.zip](https://github.com/shssoichiro/oxipng/files/10198201/Oxiorig.zip)

**Comment by TPS** [comment]
Gee, a 350KB PNG w/ 6.4MB of PhotoShop metadata attached?  That's all it takes to OxiPNG?  It's like Adobe was trying to do that.  (FWIW, lossless WebP is just 250KB.)

**Comment by andrews05** [comment]
The image library used to validate the output is running out of memory (the result is not actually corrupt). You may want to file an issue here: https://github.com/image-rs/image

@TPS +1 for JXL 😁

**Comment by TPS** [comment]
https://github.com/image-rs/image/issues/1788?
