### ISSUE TITLE
Images with a larger filesize after optimization are still overwritten

### ISSUE THREAD

**Issue by Jatie1** [shssoichiro/oxipng#485]
The following image will end up becoming bigger in size when Oxipng is run:

![test](https://user-images.githubusercontent.com/70575943/212248357-257bb4a2-9d9c-4881-9d82-fe7e9da922f8.png)

Run with the following:

oxipng -o max --strip all -a -i 0 -v test.png

Oxipng will still, for some reason, overwrite the file with the new, bigger file. Seems like unintended behavior, can others replicate?

Here is my output:
![image](https://user-images.githubusercontent.com/70575943/212249337-598d2e30-f9dc-4e33-b742-6626d11e18b9.png)

**Comment by Oondanomala** [comment]
I'm guessing it's bigger because it converts the RGB to a palette, which makes the image itself smaller but adds a lot of bytes for the palette chunk.
Oxipng probably only checks if the IDAT is smaller and not the actually file.

**Comment by TPS** [comment]
@andrews05 This seems like it might have to w/ some of your recent commits?

**Comment by andrews05** [comment]
This looks like a shortcoming of the `is_fully_optimized` function, which is supposed to catch cases where the IDAT decreased but the file size increased. If the interlacing flag is set then it will always write the output regardless. I believe the intention was that if you're requesting an interlacing change you should accept the possibility that file size may increase.

The `optimize_png` function previously had similar logic where it would force a larger IDAT if interlacing had been *added* (it looks like I mistakenly removed that part though - I should probably add it back). I think the right thing to do here would be to change `is_fully_optimized` to only force output if the interlacing flag is specifically set to 1. This wouldn't cover cases where the input is already interlaced and file size still increases, but let's be honest - who forces interlacing on anyway 🤣

**Comment by TPS** [comment]
> I think the right thing to do here would be to change `is_fully_optimized` to only force output if the interlacing flag is specifically set to 1. This wouldn't cover cases where the input is already interlaced and file size still increases, but let's be honest - who forces interlacing on anyway 🤣
> 
> Alternatively, the interlacing checks could be removed altogether and we could say that if the user wants to force interlacing on they should use the `--force` option. This is possibly a better option as it is clearer/less surprising than the current behaviour which isn't actually documented. @shssoichiro thoughts?

Since its known whether the original image is/isn't interlaced & whether the command-line options would toggle that state even before any major processing happens, couldn't output be force written only when
- command line _requires_ a change (e.g., interlacing _does_ change, chunks added/removed, image color/depth forced, &c)
- overall image size actually decreases?

**Comment by andrews05** [comment]
Yeah, that certainly could be done. It'd require a minor refactor, but the main question is around defining when the command line actually does "require" a change. Currently it's just implemented for interlacing (there are no flags to force any type of reduction), but as I mentioned this isn't actually documented and so it can be unexpected.

**Comment by andrews05** [comment]
@shssoichiro Did you have a preference on which route we should go here?
1. Change `is_fully_optimized` to only force output if the interlacing flag is specifically set to on.
2. Remove special cases for interlacing and rely on `--force` option if the user wants to force interlacing on.
