### ISSUE TITLE
If size the same, revert to original file

### ISSUE THREAD

**Issue by wenerme** [shssoichiro/oxipng#506]
I want to use oxipng for image in git repo, if size not become smaller, should use the original file.

**Comment by TPS** [comment]
I think #485 →#503 fixed this, but there hasn't been a release since.

**Comment by wenerme** [comment]
Possible to make a release ?

**Comment by ace-dent** [comment]
@wenerme - this should work as the default behaviour. Please confirm and we can Close the issue.

**Comment by andrews05** [comment]
This should be fixed in the v9 release.
