### ISSUE TITLE
Is arm64 / aarch64 architecture supported?

### ISSUE THREAD

**Issue by RDKRACZ** [shssoichiro/oxipng#518]
I wanted to optimize photos directly on Android before moving them. Also, I have a raspberry pi server.

**Comment by templarundead** [comment]
Yes

**Comment by parasew** [comment]
I can also confirm this. Issue can be closed imho.

**Comment by TPS** [comment]
Maybe there should be a section in the ReadMe for platforms that `oxipng` is confirmed to work on?

**Comment by TPS** [comment]
>> Maybe there should be a section in the ReadMe for platforms that `oxipng` is confirmed to work on?
> OxiPNG is a pure Rust project, so _a priori_ there is no reason why its AArch64 support should be worse than x64, as both targets are well supported by `rustc`.


I only meant, b/c this kind of question (& sometimes extra work, as for `wasm`) comes up periodically.

> I have some experience building Rust for AArch64 targets, so I can try adding a CI workflow for that if there is some interest.

A PR FTW! 🙇🏾‍♂️

**Comment by ace-dent** [comment]
@AlexTMjugador - fixed now?

**Comment by AlexTMjugador** [comment]
Yeah, it's now fixed, thanks for the remainder!

**Comment by TPS** [comment]
`OxiPNG` has been [added to the TUR](https://github.com/termux-user-repository/tur/pull/2134) yesterday for convenience & semi-official support! 🎉
