### ISSUE TITLE
Any way to disable "binary" feature by default?

### ISSUE THREAD

**Issue by nyurik** [shssoichiro/oxipng#519]
I suspect many oxipng lib users do not realize they are including many unneeded dependencies like clap because oxipng enables "binary" feature by default. Is there a way to make it optional, or at least place a this at the top of the readme somewhere?

```toml
oxipng = { version = "8.0", features = ["parallel", "zopfli", "filetime"], default-features = false }
```

**Comment by shssoichiro** [comment]
Unfortunately disabling a default feature isn't currently supported by Cargo, you would have to do it with the method you specified. Adding this to the readme probably does make sense.
