### ISSUE TITLE
libpng warns about invalid chunks

### ISSUE THREAD

**Issue by jansol** [shssoichiro/oxipng#52]
I recently got these warnings after recompressing a set of sprites with oxipng 0.12.0:

libpng warning: sBIT: invalid
libpng warning: bKGD: invalid

The files were compressed with `oxipng -o6 -Z sample$N-good.png --out sample$N-bad.png`

Some of the offending files:
Bad: ![sample1-bad](https://cloud.githubusercontent.com/assets/2588851/21051749/5d3c8006-be2a-11e6-9549-c850aff5c90b.png)
Good: ![sample1-good](https://cloud.githubusercontent.com/assets/2588851/21051754/5d639ccc-be2a-11e6-89c9-b0f684a051e1.png)
Bad: ![sample2-bad](https://cloud.githubusercontent.com/assets/2588851/21051751/5d632ba2-be2a-11e6-873a-10f1336048f0.png)
Good: ![sample2-good](https://cloud.githubusercontent.com/assets/2588851/21051752/5d6388f4-be2a-11e6-82eb-d85b164477e7.png)
Bad: ![sample3-bad](https://cloud.githubusercontent.com/assets/2588851/21051753/5d638200-be2a-11e6-871c-32883477c4c5.png)
Good: ![sample3-good](https://cloud.githubusercontent.com/assets/2588851/21051755/5d64b166-be2a-11e6-935b-fa700c86db97.png)
Bad: ![sample4-bad](https://cloud.githubusercontent.com/assets/2588851/21051750/5d55f608-be2a-11e6-85f7-f9e7c8bd4af0.png)
Good: ![sample4-good](https://cloud.githubusercontent.com/assets/2588851/21051756/5d70f34a-be2a-11e6-937d-d63a8d4039a1.png)
Bad: ![sample5-bad](https://cloud.githubusercontent.com/assets/2588851/21051757/5d799fb8-be2a-11e6-9815-db5c41183f94.png)
Good: ![sample5-good](https://cloud.githubusercontent.com/assets/2588851/21051758/5d7a01ce-be2a-11e6-928b-e3bc2982cfcb.png)
Bad: ![sample6-bad](https://cloud.githubusercontent.com/assets/2588851/21051760/5d7b0fc4-be2a-11e6-9f7f-ae699b43078f.png)
Good: ![sample6-good](https://cloud.githubusercontent.com/assets/2588851/21051759/5d7a9062-be2a-11e6-92bc-d6449e4c1895.png)
(I hope GitHub didn't mangle those)

**Comment by shssoichiro** [comment]
Thanks for the bug report! I'll take a look at these this evening after work.
