### ISSUE TITLE
Add man page for the command-line utility

### ISSUE THREAD

**Issue by sorairolake** [shssoichiro/oxipng#526]
I think this is useful for understanding the detailed usage of the command-line utility.

**Comment by TPS** [comment]
Probably should be done concurrently w/ #472.

**Comment by g0blin-NN** [comment]
oxipng --help > oxipng.txt

**Comment by TPS** [comment]
Given so many recent updates (most of which haven't merged, much less released), I'm not aware whether even the command-line help is current.

**Comment by g0blin-NN** [comment]
Even like this? Sorry.

**Comment by TPS** [comment]
I vaguely remember a discussion someplace in these Issues re: how out-of-date the `--help` is, & another PR recently (merged? 🤷🏾‍♂️) that is supposed to (partially? 🤔) solve that.

**Comment by andrews05** [comment]
`--help` has been kept up-to-date with all changes, it's just the Read Me that may be out of date.

@sorairolake Not saying there shouldn't be a man page, but was there something in particular you were wanting to understand that wasn't explained sufficiently in `--help`?

**Comment by sorairolake** [comment]
@andrews05 I also think the usage in `--help` is explained sufficiently. However, I think it would be more useful to be able to see how to use `oxipng` on the web (such as <https://man.archlinux.org/>) or a console.

**Comment by andrews05** [comment]
One easy thing we could do is append the help output to the Read Me (in some sort of automated fashion). This would at least make it easily accessible online.

**Comment by musicinmybrain** [comment]
You might (or might not) find `clap_mangen` ([GitHub](https://github.com/clap-rs/clap/tree/master/clap_mangen), [crates.io](https://crates.io/crates/clap_mangen)) useful for this.

**Comment by andrews05** [comment]
Thanks @musicinmybrain, see #596 where I’m using that 🙂 
I hope to pick that up again soon and see if I can make a deb package…
