### ISSUE TITLE
Portable Network Graphics (PNG) Specification (Third Edition)  W3C Working Draft 20 July 2023

### ISSUE THREAD

**Issue by parasew** [shssoichiro/oxipng#538]
Not sure if there is an instant action item, but here is the [W3C Working Draft](https://www.w3.org/standards/types#WD) of the PNG spec of 20 July 2023 (today).

Here are the [changes since the 2nd edition of PNG](https://www.w3.org/TR/png-3/#changes-20031110):

- APNG has been added to the spec
- A new CICP chunk that paves the way for HDR support
- EXIF is part of the main spec

Wondering if oxipng would be covering APNG

**Comment by andrews05** [comment]
Nice, thanks for sharing. 
Interesting to hear APNG is now official. Initial support for this was added to oxipng in #511. 
cICP is also explicitly preserved by the safe strip option.

**Comment by TPS** [comment]
Full APNG compression support is being tracked in #551.

**Comment by andrews05** [comment]
Preliminary APNG support is now released.

**Comment by C0rn3j** [comment]
For people landing here and wanting to read more about the new PNG Third Edition just like I did:
* Changelog that OP linked[^3] should be read from the linked page upwards for newer spec releases, reading downwards is just second edition changes and older, it's a bit confusing as the fragments do not contain their own date.
  * At the time of writing, spec repo has newer changelog[^1] than the current website
* Spec repo has a nice Third Edition explainer[^2] document

[^1]: https://github.com/w3c/PNG-spec/blob/main/index.html#L7547 - CTRL+F for `F-ChangeList` if line is out of date
[^2]: https://github.com/w3c/PNG-spec/blob/main/Third_Edition_Explainer.md
[^3]: https://www.w3.org/TR/png-3/#changes-20031110

**Comment by svgeesus** [comment]
The best link to keep up with changes to PNG third edition is
  https://w3c.github.io/PNG-spec/#F-ChangeList

Glad the explainer is helpful!
