### ISSUE TITLE
Option for target size

### ISSUE THREAD

**Issue by bend-n** [shssoichiro/oxipng#544]
Ive found that oxipng is *too good*: it optimizes images far more than I need. Setting the time limit makes it sometimes fail to optimize at all.

The solution: size target!

It seems to be possible to check what the new png size is, at the same time as the deadline check.

**Comment by ace-dent** [comment]
How would you know the size target in advance? Some images compress better than others, depending on content... 
Surely if you need more speed at the cost of some bytes, just use a lower `-o` level?...

**Comment by andrews05** [comment]
Hi @bend-n, this does seem like a pretty strange request 😄
I'm afraid a size target setting would not be feasible to implement. If you're wanting it to be faster your only option is to adjust the optimisation settings to find a point that you're happy with.

If you can tell us a bit about your situation we may be able to make some suggestions.

**Comment by bend-n** [comment]
- what im doing: compressing 12k images, at -o0.
- the problem: it takes upwards of 12 seconds.
- the feasability:
ive been trying to implement this myself, and ive noticed that [`Evaluator::try_image`](https://github.com/shssoichiro/oxipng/blob/02bd47ba297ffdc1210c89b6f98c0d2c4b31d155/src/evaluate.rs#L112) sets [`best_candidate_size`](https://github.com/shssoichiro/oxipng/blob/02bd47ba297ffdc1210c89b6f98c0d2c4b31d155/src/evaluate.rs#L77). You can then easily check it in [`reduction.rs`](https://github.com/shssoichiro/oxipng/blob/02bd47ba297ffdc1210c89b6f98c0d2c4b31d155/src/reduction/mod.rs#L41).

that part has been simple to implement; i havent yet got it to work with the filters however.

**Comment by andrews05** [comment]
Interesting, you're already using the fastest setting. Some things you could still try to make it faster:
- Use an even lower compression level, e.g. `--zc 3`.
- Disable certain reduction types using the `--n*` flags.

How many hardware threads do you have?
Would you mind posting one of the images? I'd be interested to see what reductions are occurring and where the bottlenecks are. I'm assuming the images are all of a similar style?

**Comment by bend-n** [comment]
Well im using the library with the `parallel` feature off as the server im putting this on only has 1 thread.
Im aiming for a size target of <10mb.

Do you want to see the uncompressed image? Or is the compressed image fine?

**Comment by andrews05** [comment]
Uncompressed would be best.

**Comment by andrews05** [comment]
Cool, thanks for that!

This image essentially goes through 6 steps:
1. Decoding/decompressing
2. Converting RGBA to RGB
3. Converting RGB to Indexed
4. Sorting the palette
5. Filtering with Bigrams strategy (chosen automatically according to image type)
6. Encoding/compressing

Step 1 is actually taking the most amount of time. Possibly we can investigate to see if this can be improved.
Step 2 is redundant (but it doesn't know this in advance). Skipping it might save about 10% in time but there's no options to do so currently.
Step 3 is important as it reduces the amount of data to be compressed. Without this not only would the file be larger but the filtering and compression would actually take longer.
Step 4 is unimportant but doesn't appreciably affect speed.
Step 5 is relatively slow and in this case not even the best choice. **If you override this by explicitly using the `None` filter you can save about 20% in total time taken.**
Step 6 is pretty fast. Lowering the compression level to 1 doesn't make much of a difference.

Note there's only one compression trial that happens here so there's not really any opportunity to bail early.

**Comment by bend-n** [comment]
so i need all the reductions, but not the filter?

**Comment by andrews05** [comment]
Sorry, got that wrong - I've edited to indicate you may not need the reductions either.

If you're building off current master you can actually use the new Raw API to avoid creating a PNG beforehand.

**Comment by bend-n** [comment]
its a fair bit faster now, raw api is awesome! i also looked at the code a little more, and decided that the only part the target size would help with was reductions, which are already fast.
