### ISSUE TITLE
`--recursive` flag trys to compress non png files

### ISSUE THREAD

**Issue by LuckyTurtleDev** [shssoichiro/oxipng#547]
The `--recursive` flag, does also try to compress non png files (even it is not even an image). Is their any reason, why the files are not filtered by `.png` extension? This should speed up the recursive flag, since non `png` files need not be considered.

I can implement this, if this feature is wanted.

**Comment by andrews05** [comment]
This seems very sensible, I guess it's just never come up before. Feel free to open a PR 🙂

**Comment by TPS** [comment]
@LuckyTurtleDev If you _are_ implementing this, maybe consider an option to retain the current behavior, as well?

**Comment by andrews05** [comment]
Note that regardless of how `--recursive` works, you can always use globbing to do the same thing. `**` for everything, `**/*.png` for just png files. So we really don't need two options for it.
(I realise this kind of globbing may be foreign to Windows users, but I'm pretty sure it does work in oxipng)

**Comment by XhmikosR** [comment]
The problem is that due to the Windows globbing issues, `--recursive` is still the only way to recursively optimize folders. At least up until #536, which seems to work (I tested the build from CI PR).

**Comment by TPS** [comment]
Globbing is brittle on Windows (e.g., search "glob" in this repo's issues/PRs/commits & you'll see what I mean), b/c it's _not_ shell/system function, so switches like this are preferred there.

**Comment by LuckyTurtleDev** [comment]
I have impl this now and include an flag to keep the old behavior.
