### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by laurmaedje** [shssoichiro/oxipng#552]
Hey, are there any plans to make a new crates.io release soon-ish? I just ran into the rayon [deadlock](https://github.com/shssoichiro/oxipng/issues/517) issue, which was fixed a while ago and wondered why there hasn't been a release in a longer time even though many improvements have been merged.

**Comment by AlexTMjugador** [comment]
There are a few PRs that have to be resolved before the next release (see https://github.com/shssoichiro/oxipng/pull/529#issuecomment-1717223698), but I expect the work required to complete them to be relatively minor. Once they are resolved, I don't see any reason not to make a new release.

Given Josh's words in https://github.com/shssoichiro/oxipng/issues/189 about maintainer responsibilities, I think it'd be appropriate for @andrews05 and I to help with the release, but let's see what they think!

**Comment by andrews05** [comment]
@shssoichiro If you're wanting to step back more and are happy for @AlexTMjugador and I to merge PRs and manage releases, just let us know. It's great having your input and oversight but understand if this just isn't something you have time for at the moment.

**Comment by shssoichiro** [comment]
@andrews05 That would actually be great, although I try to keep up with MRs here it's been tough also keeping up with day job + other life things. I don't think I necessarily need to be the one pushing the buttons anymore.

I tried sending you an invite on crates.io to manage releases but it looks like you may need to create an account there first. Once you do I'll get the invite sent. :+1:

**Comment by AlexTMjugador** [comment]
Great to hear that, @shssoichiro! I also think that your input is very welcome no matter what. Feel free to invite me too on crates.io if you feel it's appropriate :smile:

**Comment by shssoichiro** [comment]
@AlexTMjugador Sent!

**Comment by andrews05** [comment]
@shssoichiro Great, I've just created an account 🙂

**Comment by AlexTMjugador** [comment]
Just sent an invite @andrews05 :wink:

**Comment by andrews05** [comment]
@shssoichiro I wonder if it would worth setting up an org and transferring the repo there. That would give greater control over permissions etc.

@AlexTMjugador I'll wait for your approval on those PRs before merging.

**Comment by AlexTMjugador** [comment]
> I'll wait for your approval on those PRs before merging. Are you expecting another zopfli release soon?

Okay, I'll review them soon!

About the `zopfli` release, I'm kind of holding on it because I wanted it to contain more substantial changes, but given that several stable micro-optimizations and improvements here and there have been made, I think it's a good idea to release it so OxiPNG and other dependencies can more readily take advantage of that. So I'll try to get that released soon, too.

**Comment by AlexTMjugador** [comment]
Now that the PR queue is almost empty, I think it's a good time to prepare the [changelog](https://github.com/shssoichiro/oxipng/blob/master/CHANGELOG.md) for the upcoming release. @andrews05, would you like to take care of that?

**Comment by andrews05** [comment]
Will do! I've been keeping draft release notes on the releases page, so feel free to review there before I prepare a PR.

**Comment by ace-dent** [comment]
Reminder for new release, to update [homebrew](https://github.com/Homebrew/homebrew-core/blob/c0d6037f80f5032d760c22fb4e68d5f76b98573c/Formula/o/oxipng.rb) and other distribution sources as per #69.
