### ISSUE TITLE
`--zopfli` and `--timeout` conflict

### ISSUE THREAD

**Issue by Winterhuman** [shssoichiro/oxipng#556]
Version: oxipng 8.0.0

I wasn't sure whether the `--help` page needed a statement stating that they can't be used together (otherwise `--timeout` is ignored), or if this should be a feature request for letting `--zopfli` be timed out.

Let me know what you think, I'd be happy to open a pull request for adjusting the `--help` page if supporting both isn't possible to implement (though I might need help figuring out which file to modify).

**Comment by andrews05** [comment]
Hi @Winterhuman 
The `--timeout` flag is unfortunately not well supported right now, and this is not specific to zopfli - the default libdeflate compressor also does not adhere to it. There's simply no easy way to do so with the APIs available. I guess we've kept the flag in the hope that one day it might be improved, but I guess we should update the help to indicate that it isn't as effective as you might expect.

**Comment by Winterhuman** [comment]
Ah I see. Do you want me to send a PR to add the notice?

Note to self: https://github.com/shssoichiro/oxipng/blob/master/src/main.rs#L259

**Comment by andrews05** [comment]
Sure, that would be helpful. To clarify what it does currently:
1. Images go through a series of reductions/transformations. The timeout is checked before performing each one.
2. Certain reductions are entered into a fast compression evaluator to see which one is best. The timeout is checked before performing each evaluation.
3. The winning reduction goes through full-strength compression trials for each enabled filter (up to 10). The timeout is checked before performing each compression. This is the point where it matters the most - steps 1 and 2 are very fast so it doesn't matter much there.

In previous versions of oxipng, there were many more zlib compression trials (hundreds, depending on the settings). These were relatively fast and the timeout was checked for each one, allowing an early abort while still (hopefully) giving a compressed output. This doesn't work so well in the current architecture where libdeflate (or zopfli) is stronger but slower and we only do a handful of trials.

Out of interest, how/why are you using the timeout currently? Would using coreutils `timeout` command work for you instead?

**Comment by Winterhuman** [comment]
I was thinking about using `--timeout` because of the long wait time associated with using `--zopfli` (which is probably because it's single-threaded), it can take up to 10 and a half minutes (5 and a half with `--fast`), and I thought I might be able to cut it short slightly.

**Comment by andrews05** [comment]
Right, so the `--opt` level does indeed change the number of filter trials (each level is detailed in the help). But if you add `--fast` it evaluates all the filters using fast compression, then performs only a single full-strength compression of the best result. This is generally recommended (particularly with zopfli), but it does mean there's no way to cut it any shorter if you still want to get a result. I'm assuming you're still wanting to get a result, rather than total abort when the timeout is reached?

**Comment by Winterhuman** [comment]
Yes, however for what I'm doing, where I'm trying to find the smallest possible encoding of an image using various optimisation tools (I've got some weird results, but I'm waiting on the next release in case it fixes this), I probably couldn't use a lower number of compression rounds anyway the more that I think about it.

**Comment by Winterhuman** [comment]
More generically though, being able to use Zopfli, but without needing all compression trails, would still be useful for more normal use-cases.
