### ISSUE TITLE
Strange OxiPNG + PNGQuant results (+dev build results)

### ISSUE THREAD

**Issue by Winterhuman** [shssoichiro/oxipng#558]
I've noticed that feeding images through `pngquant` first (in a lossless way using `-Q 100-100`) before passing it to `oxipng` can create wildly different output sizes, causing significantly smaller or larger outputs (it even beats `--zopfli` on some occasions).

And, using the dev build linked in https://github.com/shssoichiro/oxipng/pull/554#issuecomment-1734555309, I found that the build didn't correct this anomaly. In response, I created a Gist containing the sizes of images I found to be particularly strange.

Link to image results: https://gist.github.com/Winterhuman/d19889d0d44c6403c8b43d3803c5cf55

Link to ZIP containing the original PNGs: [Original-images.zip](https://github.com/shssoichiro/oxipng/files/12720738/Original-images.zip)

**Comment by andrews05** [comment]
Thanks for the data.
I'm a little unsure what pngquant actually *does* at Q100. It's a lossy optimiser by nature, so I would have thought 100 would effectively be a no op. Probably what you're seeing is simply caused by a different ordering of the colour palette - sometimes it compresses better, sometimes worse. Palette sorting is unfortunately not an exact science.

**Comment by TPS** [comment]
> Thanks for the data.
> I'm a little unsure what pngquant actually *does* at Q100. It's a lossy optimiser by nature, so I would have thought 100 would effectively be a no op.

@andrews05 I suppose posting @ https://github.com/ImageOptim/libimagequant → https://github.com/kornelski/pngquant could answer much of that?

@kornelski _did_ provide much of the massive early work here on `oxipng` & still recommends it in conjuction w/ `pngquant`, so might be willing to give some pointers?

**Comment by kornelski** [comment]
For larger images it's a difference between grayscale and palette image (palette with few colors apparently compresses better). For small images it's palette order.

**Comment by Winterhuman** [comment]
Yeah, this seems like an unfortunately random thing, and trying to brute-force search for the perfect colour palette when there's even a smaller number of colours is basically impossible; a palette of just 8 colours would have 40,320 permutations.

**Comment by Winterhuman** [comment]
Perhaps a `--filters` like system of trying a couple different sorting strategies in parallel could work? I have no idea what that'd look like though given estimating how compressible something is without compressing it isn't an exact science either from what I can tell.

**Comment by kornelski** [comment]
https://www.researchgate.net/publication/51371279_A_Survey_on_Palette_Reordering_Methods_for_Improving_the_Compression_of_Color-Indexed_Images

**Comment by Winterhuman** [comment]
"We concluded that the pairwise merging heuristic proposed by Memon et al. is the most effective, but also the most computationally demanding. Moreover, we found that the second most effective method is a modified version of Zeng's reordering technique, which was 3%-5% worse than pairwise merging, but much faster."

Okay, that's good news then! Great find @kornelski

**Comment by ace-dent** [comment]
@kornelski - you may wish to review the recent palette work in #514.

**Comment by andrews05** [comment]
Great, this sounds like it's settled it then :)
You can read #514 to find out all about oxipng's current palette sorting techniques, comprised of a modified luma sort and a Battiato sort.

@Winterhuman feel free to close if you're satisfied with the answers.

**Comment by Winterhuman** [comment]
Seems like there's a potential way of forward, I'm happy with that. Should I keep this issue open until a pull containing one of the mentioned algorithms is merged, or would you prefer I close the issue now?

**Comment by andrews05** [comment]
That would be largely unrelated to your original question and pngquant, so I think we can close this.
I believe pngquant implements a popularity sort, @kornelski? Basically, any type of sort which isn't the same as oxipng's has a chance of being better in certain cases, even if oxipng is much better on average. In general though, I'd say you're better off trying other dedicated lossless optimisers than running pngquant at Q100.

Algorithms we intend to explore further are the mzeng method mentioned above, plus one or two others I forget the name of right now but have in my notes somewhere 😅

**Comment by Winterhuman** [comment]
Makes sense, I'll close this issue then. Looking forward to the new release!
