### ISSUE TITLE
Documented default for `--interlace` is wrong

### ISSUE THREAD

**Issue by Yay295** [shssoichiro/oxipng#565]
The 9.0.0 release notes say that the default for `--interlace` has been changed to `keep`, but `--help` still says the default is `0`.

**Comment by andrews05** [comment]
The release notes say it defaults to removing interlacing and suggests to use `-i keep` if you need to preserve. Perhaps it could be clearer?

**Comment by ace-dent** [comment]
@Yay295 - Please can you read again the release notes, to check the statement is clear?

**Comment by Yay295** [comment]
Huh, it does say that. How did I misread that...?
