### ISSUE TITLE
Winget distribution

### ISSUE THREAD

**Issue by Maingron** [shssoichiro/oxipng#567]
Can we have oxipng through winget? Would be cool if oxipng could be installed by just running `winget install oxipng`.  

Winget is Windows' native CLI Package Manager and I prefer it to install most of my programs. I tried choco and others over the year, but those always seemed to bug out eventually and they also don't integrate as well as winget into the system imo.  

See: https://learn.microsoft.com/en-us/windows/package-manager/package/repository and https://github.com/microsoft/winget-pkgs

Same question goes for apt on Linux, but I don't want to flood the issues with the same question for both.

**Comment by andrews05** [comment]
Thanks for the suggestion, this looks like a good idea.

It appears that it requires us to provide an "installer" (MSIX, MSI, or EXE) for oxipng, not just the program itself. I don't have any experience in such matters, so I'm afraid I won't be able to action this myself. I guess we would need to create this as part of the deploy process.
@AlexTMjugador do you have any knowledge here?

**Comment by Maingron** [comment]
Ooops, sorry for kicking you down into those holes. ...Hopefully one day.

Has anyone looked into the situation for apt on Linux? I'm afraid to ask

**Comment by AlexTMjugador** [comment]
> Has anyone looked into the situation for apt on Linux? I'm afraid to ask

APT is much better in this regard. [`cargo-deb`](https://github.com/kornelski/cargo-deb) makes it easy to generate proper .deb files that developers can reason about if necessary. The only pain points with APT are the distribution of the .deb packages and the fact that not every Linux environment uses the APT package manager or Debian-compatible repositories (distros like Fedora or Arch Linux, for example, use different package managers).

Elaborating on the distribution of .deb packages, it is not common in the Linux world to download random .debs from the Internet and apt install them, so setting up APT repositories for easier updating and management is preferred. Fortunately, [there are easy ways to turn a GitHub repository into an APT repository](https://github.com/marketplace/actions/github-pages-apt-repo).

**Comment by TPS** [comment]
> > I have tried packaging Rust applications before, and I came to the conclusion that properly packaging Windows software, especially when not relying on Visual Studio-centric development environments, is hard:

> Fortunately, [there are easy ways to turn a GitHub repository into an APT repository](https://github.com/marketplace/actions/github-pages-apt-repo).

There seems to be [something similar](https://github.com/vedantmgoyal2009/winget-releaser) for WinGet, once 1 release has been allowed into that repo?

**Comment by andrews05** [comment]
There's an open request for oxipng to be adopted into Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913285

**Comment by AlexTMjugador** [comment]
> I'm not sure creating our own apt repo is particularly helpful - it really needs to be in the defaults repos. I believe it's currently available in both Alpine and Arch Linux.

Users can add any repository they want to their APT configuration, and software like [Docker](https://docs.docker.com/engine/install/debian/#install-using-the-repository) maintains custom repositories to circumvent distribution politics and policies. But yes, an ideal outcome would be for OxiPNG to be adopted in the official Debian repositories, as this should provide the best experience for the end users of this distribution (as long as the package is reasonably well maintained, not shipping a years-old, subpar OxiPNG version that misleads users into thinking OxiPNG is really like that... 😅).

**Comment by RossSmyth** [comment]
May be worth it to look in to https://opensource.axo.dev/cargo-dist/ since it can produce [many distribution artifacts](https://opensource.axo.dev/cargo-dist/book/installers/index.html#supported-installers) with GitHub actions. Currently winget isn't supported, but MSI installers are. Winget (and Docker images as another issue requests) is planned so eventually it could be automated.

**Comment by AlexTMjugador** [comment]
It seems that `winget` doesn't currently require a full-fledged installer, which allowed @stevenlele to easily submit a PR to add Oxipng as a `winget` package [here](https://github.com/microsoft/winget-pkgs/pull/170613)! 🎉

This means Oxipng is now distributed through `winget`, so I'm closing this issue as resolved.
