### ISSUE TITLE
Replace miniz with pure-Rust deflate library

### ISSUE THREAD

**Issue by shssoichiro** [shssoichiro/oxipng#57]
This requires finding (or creating) a pure-Rust deflate library, capable of compressing and decompressing, with approximately the same performance as miniz.

**Comment by bvinc** [comment]
My understanding is that there are only 2 zlib encoders written in pure rust.  One is zopfli.  The other is the crate "deflate", which is what piston's png library now uses.  https://github.com/oyvindln/deflate-rs  I'm not sure about its performance compared to miniz.

**Comment by joshtriplett** [comment]
Having an option to use zopfli would be nice, if you want to take a huge amount of time to potentially gain further compression.

**Comment by shssoichiro** [comment]
This exists now: https://github.com/Frommi/miniz_oxide
