### ISSUE TITLE
Support NO_COLOR option for CLI

### ISSUE THREAD

**Issue by ace-dent** [shssoichiro/oxipng#574]
Add support for NO_COLOR env var; see https://no-color.org/

**Comment by TPS** [comment]
It seems a bit complex?  IIUC, this is looking to make command-line color text output _always_ be opt-in (via other environment variables or command-line options) than opt-out.

The good news is that there are Rust CLI crates (listed on the site) that already support this, so, if 1 of these is _already_ used, maybe very little additional support is needed other than perhaps the specific supported argument to turn color text on?

**Comment by andrews05** [comment]
This already work for me, have you tried it?

**Comment by TPS** [comment]
@andrews05 That's excellent news indeed!

**Comment by ace-dent** [comment]
@andrews05 test on macOS with `env 'NO_COLOR=1'`. Not working for me.

**Comment by andrews05** [comment]
@ace-dent Note that `env` only applies when executing a command on the same line, as in `env NO_COLOR=1 oxipng ...` (or just `NO_COLOR=1 oxipng ...`).
To retain the var for your current session use `export NO_COLOR=1`.

**Comment by ace-dent** [comment]
@andrews05 Thanks! User error! 😄 
Closed.
