### ISSUE TITLE
Failed to set permissions, expected: 100666, found: 100644

### ISSUE THREAD

**Issue by Jaiyce87** [shssoichiro/oxipng#576]
Hi,

I'm having an issue where files with permissions different than 644 cannot be optimized using both "--preserve" and "--out".
Here are my system info: Arch Linux 64-bit, Kernel 6.6.1-arch1-1, oxipng `9.0.0-1` from the Arch extra repository.

Here are some steps to reproduce the issue:
1. `chmod 666 image.png`
2. `oxipng -o max image.png --preserve --out image-optimized.png`
> image.png: failed to set permissions, expected: 100666, found: 100644

I tried to create the destination file with correct permissions before running oxipng tool and this worked.
1. `touch image-optimized.png`
2. `chmod --reference=image.png image-optimized.png` 
3. `oxipng -o max "image.png" --preserve --out "image-optimized.png"`

I tried to look in [oxipng/src/lib.rs](https://github.com/shssoichiro/oxipng/blob/master/src/lib.rs) where the error is raised (line 1046) but I sadly don't know much about Rust and can't tell if something is off or if it's my system that's improperly configured.

I haven't seen similar opened issues, sorry if this is a duplicate! 
Also, this is my first time using Github, excuse me if anything is wrong with this report.

Thank you in advance for your help and have a nice day!

**Comment by AlexTMjugador** [comment]
Thanks for the report! You made a really nice description of the problem and how to reproduce it for this being your first time 😄

I've coded a fix for it in #578. Assuming it gets a favorable review and merge, the next release should fix this. Please feel free to try the unstable builds that CI will generate for this PR and comment on whether they fix the problem for you.
