### ISSUE TITLE
Announcing CPNG, "Compatible Network Graphics", a backwards compatible fork of PNG 

### ISSUE THREAD

**Issue by parasew** [shssoichiro/oxipng#585]
I wanted to point everyone here to [CPNG](https://richg42.blogspot.com/2023/12/announcing-cpng-compatible-network.html), and the discussion on [hackernews](https://news.ycombinator.com/item?id=38554281). What do we generally think about CPNG?

**Comment by ace-dent** [comment]
Seems like an odd direction; if the target is decoding speed over storage, use a simpler bitmap format...? HDR and extended colour profiles seem to be in progress for PNG spec v3, so will become mainstream. I think even today, delay is in transmitting rather decoding. Hence the effort with JXL.

**Comment by TPS** [comment]
IMHO, seems like a tractionless "solution" to #561.… 🤷🏾‍♂️

**Comment by andrews05** [comment]
Thanks for posting this! It’s quite interesting but I don’t think this is something oxipng needs be involved with. If it ever gains widespread adoption we could certainly consider it then.

<details><summary>Opinion</summary>
[I’m hiding this as it’s not relevant to oxipng and it would probably be better to keep discussion on hackernews.]

While I commend the efforts here I can’t see this ever gaining any traction. I just can’t imagine any major players having any interest in adopting yet another format, especially one that isn’t even an official spec. Not to mention HDR is already possible via cICP and the major players are putting all their HDR efforts into AVIF and (hopefully) JPEG XL. There’s just no demand for this (that I can see). I also generally agree with comments in the discussion from solardev.

My dream for oxipng is actually that one day JPEG XL will become as ubiquitous as JPEG and there will be no need for optimising pngs anymore. I’m not placing any bets on when or if that will ever happen though 😆
</details>
