### ISSUE TITLE
File process order?

### ISSUE THREAD

**Issue by someonenameguy** [shssoichiro/oxipng#586]
Is there a way to tell oxipng to process file in like "Time Created Descending" or "Last Modified First"?

_I mistakenly pressed enter on my phone while trying to type so this was empty._

**Comment by ace-dent** [comment]
This sounds like something you can achieve with your shell/ OS...? Or perhaps with a command line script? Could you describe your use case in more detail?

**Comment by andrews05** [comment]
Yeah, if you're using zsh for instance, you can use [glob qualifiers](https://zsh.sourceforge.io/Doc/Release/Expansion.html#Glob-Qualifiers) to change the order (see `oc` and `Oc`).
E.g.
```zsh
for file in *.png(Om); do
    oxipng $file
done
```
Note I'm using a loop here as oxipng's rayon thread pool will not guarantee order if you just feed them all in directly.

**Comment by someonenameguy** [comment]
I have a folder where images are saved automatically(eg. downloads) but there no name scheme. All the pngs in it have been ran through oxipng and been optimized. Now I save new images then run:
`oxipng -rpo 1 .\` it seems to process some of the old file first then the new ones then the old ones.
The file have correct modif and create time stamps so I was wondering if oxipng could use that.

I asked chatgpt about `glob qualifiers` for windows and termux, it seems there a way to do it in the ?os?.
`for /f "delims=" %%a in ('dir /b /o-d /tw') do set "filename=%%a"` for windows and `for file in $(ls -t); do` for termux.

If I missing some easier way to do it inside of oxipng please tell.
If not, you can close this.

**Comment by andrews05** [comment]
There's no way to do this with oxipng itself I'm afraid.
It sounds like what you're really wanting to do is skip files that have already been processed. This is also not possible with oxipng itself (see #549) but perhaps you could move the files to another folder after processing?
