### ISSUE TITLE
[Question] The order of files that gets processed changes randomly?

### ISSUE THREAD

**Issue by someonenameguy** [shssoichiro/oxipng#590]
![Screenshot_20240216_232645_Termux](https://github.com/shssoichiro/oxipng/assets/54163580/0b53fa1b-05b6-4d5d-8759-bec4f071b94e)
In the red boxes the filenames changes randomly even thought the files are already sorted by name, only the first one stays the same.
Anyone knows what's happening?

**Comment by andrews05** [comment]
oxipng processes multiple files in parallel, adding each one to a thread pool. The order that files will be completed is indeed non-deterministic. You can disable this if necessary by setting `--threads 1`.

**Comment by someonenameguy** [comment]
I see. I'll set it to single-thread for future processing.

**Comment by andrews05** [comment]
Alternatively you can execute oxipng separately for each item, which allow it to still use multiple threads for optimisation. You may be able to do this by adding `-L 1` to xargs, or by using a loop as I mentioned in your previous thread https://github.com/shssoichiro/oxipng/issues/586#issuecomment-1859008169 (apologies if I closed that prematurely, did you manage to get it sorted by time?).

**Comment by someonenameguy** [comment]
I kinda give up trying to sort by time since the files in `Twitter\X` are named by date and some id. so doing `ls` sorts them by date.

I just tried running `ls -rw 1 | xargs -r -L 1 oxipng -po 4 ` it to runs the same as `-threads 1`.
I checked with echo seems fine though.
```bash
ls -rw 1 | xargs -r -L 1 echo oxipng -po 4 
...
oxipng -po 4 20240114_163924.png                               oxipng -po 4 20240101_165454.png
oxipng -po 4 20231229_104644.png                               oxipng -po 4 20231229_104456.png
oxipng -po 4 20231229_104356.png                               oxipng -po 4 20231228_214504.png
oxipng -po 4 20231223_182621.png                               oxipng -po 4 20231221_123639.png
oxipng -po 4 20231218_011109.png                               oxipng -po 4 20231218_011107.png
oxipng -po 4 20231205_163829.png                               oxipng -po 4 20231205_071650.png
oxipng -po 4 20231130_233753.png                               oxipng -po 4 20231127_075119.png
oxipng -po 4 20231127_075118.png                               oxipng -po 4 20231124_003135.png
oxipng -po 4 20231124_002800.png                               oxipng -po 4 20231123_161119.png
oxipng -po 4 20231123_161114.png                               oxipng -po 4 20231117_123806.png
oxipng -po 4 20231111_095818.png                               oxipng -po 4 20231111_004448.png
oxipng -po 4 20231111_003354.png                               oxipng -po 4 20231111_003352.png
oxipng -po 4 20231110_083845.png                               oxipng -po 4 20231110_072440.png
^C
```

The looping one doesn't work simply because termux uses Bash not Zsh, I get and error on the `(Om)` part.
```Bash
for f in *.png(Om); do oxipng -po 4 $f; done
bash: syntax error near unexpected token `('
```

**Comment by andrews05** [comment]
> I kinda give up trying to sort by time since the files in `Twitter\X` are named by date and some id. so doing `ls` sorts them by date.

Ah right, that seems sensible.

> I just tried running `ls -rw 1 | xargs -r -L 1 oxipng -po 4 ` it to runs the same as `-threads 1`. I checked with echo seems fine though.

Yeah, so the advantage is it should be noticeably faster than completely disabling multithreading.

**Comment by someonenameguy** [comment]
> Yeah, so the advantage is it should be noticeably faster than completely disabling multithreading.

oxipng uses multi-threading for single images? Didn't know that, I use `ls -rw 1 | xargs -r -L 1 oxipng -po 4 ` in the future. 
At least only 1477 of 22888 files in there are pngs.

Thanks/Thank you for the help be the way.
