### ISSUE TITLE
Enhance processing of 'dirty alpha'

### ISSUE THREAD

**Issue by ace-dent** [shssoichiro/oxipng#597]
Using oxipng with `-a` to alter RGB values for fully transparent pixels, may not always yield optimal results.
See attached examples.

Original (52,385 bytes):
![logo](https://github.com/shssoichiro/oxipng/assets/473224/7b04eb2f-2702-4d7d-abb0-f47d0849231c)

Processed with oxipng (50,264 bytes) ... and alpha stripped to reveal underlying RGB :
![logo-oxipng](https://github.com/shssoichiro/oxipng/assets/473224/f4d8374a-b5dc-4801-9411-c8cd9dd5ec4c) ![logo-oxipng-opaque](https://github.com/shssoichiro/oxipng/assets/473224/9f850db0-46df-4436-a6a5-49ef147d28bd)

Processed with FileOptimizer (49,762 bytes) ... and alpha stripped to reveal underlying RGB :
![logo-FileOptimizer](https://github.com/shssoichiro/oxipng/assets/473224/1ed1af97-417e-41d2-89ba-4aa54b380b7c) ![logo-FileOptimizer-opaque](https://github.com/shssoichiro/oxipng/assets/473224/73de1e26-4271-44b3-bb6f-16eb5abc6b6c)

Is there scope in the current process to evaluate simpler 'dirty alpha' fills?

**Comment by andrews05** [comment]
Could you post the options you're using? I'm getting 50,334 with `-saZo6`.

**Comment by ace-dent** [comment]
@andrews05 - it has gone through some other software. However, the issue of low -vs- high complexity alpha fill should be repeatable.

**Comment by andrews05** [comment]
I tried putting with low complexity one through oxipng with `-sZo6 --force` (no alpha) and it came out at 50,333, only 1 byte difference. So I'm not sure the alpha is really a factor in the size difference you're seeing above - it may simply come down to better compression or filtering.

**Comment by ace-dent** [comment]
Thanks @andrews05 for testing and comments.
I'm new(ish) to this area of optimization... but more from intuition, the oxipng image seems to introduce higher entropy... I will be testing more in future. :-)
Feel free to Close in the meantime.

**Comment by andrews05** [comment]
> from intuition, the oxipng image seems to introduce higher entropy

It sure does appear that way. However, appearances can be deceiving 😉 
The alpha optimisation works by setting all the underlying values to 0 (more or less). As the filter changes for each line it makes for an interesting appearance when the image is decoded.
