### ISSUE TITLE
Add docker release images

### ISSUE THREAD

**Issue by ilya-hontarau** [shssoichiro/oxipng#610]
It will be good to build and push on each release an image to dockerhub.

**Comment by andrews05** [comment]
Hi @ilya-hontarau, sorry for the late reply. We're just trying to sort out the current release and then we can look into this.

Out of interest, may I ask what is your use case?

**Comment by peterdeme** [comment]
@andrews05 we are using precommit with an oxipng hook. a few of our team members are too lazy to download precommit, and just manually run oxipng instead. particularly, manually run oxipng via Docker.

some dude posted an oxipng Docker image a year ago but that's outdated now. https://hub.docker.com/r/videah/oxipng

**Comment by andrews05** [comment]
Just as a test, I've published an image under my own user: https://github.com/andrews05/oxipng/pkgs/container/oxipng
If this is helpful we can look at setting up a workflow (don't rely on this one to stick around forever).

I guess I'm a little puzzled by the need to use docker to run a single binary with no dependencies. Wouldn't it be easier for your team members to just install oxipng directly?

**Comment by peterdeme** [comment]
@AlexTMjugador 

In general people like to _not_ download stuff unless they need to.

```
docker run --rm -v $PWD:/workspace author/oxping /workspace/assets/screenshot_01.png
```

**Comment by AlexTMjugador** [comment]
Thanks for the clarification! I also try to avoid downloading stuff I don't need, but Docker images have to be pulled (i.e., downloaded) before use anyway. A Docker image is, for this purpose, just another way of downloading the binary, but with extra overhead for the image metadata and such. It doesn't really get more portable, or require less system modifications to set up.

However, I'm thinking that a Docker image could be useful if you're looking into scaling with Kubernetes, so you can spawn OxiPNG containers to handle incoming requests as required. That integration is, frankly, something that cannot be achieved well without Docker images. What do you think about this?
