### ISSUE TITLE
Add man page to the brew package

### ISSUE THREAD

**Issue by pereorga** [shssoichiro/oxipng#615]
A man page can now [be generated](https://github.com/shssoichiro/oxipng/pull/596), but is not being included when installing the package using `brew`:

```
$ brew install oxipng
Warning: oxipng 9.1.1 is already installed and up-to-date.
To reinstall 9.1.1, run:
  brew reinstall oxipng

$ man oxipng
No manual entry for oxipng
```

**Comment by andrews05** [comment]
Hi @pereorga, sorry to hear this but this is probably expected at this point. Oxipng maintainers don't control any of the external distributions - each of them will need to make changes to their packaging to accommodate the new man page. Try reporting this to homebrew.

**Comment by andrews05** [comment]
It appears homebrew actually added the manpage just after this issue was created. I'll wait until they have it working for v9.1.3 before closing this though, as the way the manpage is generated has been changed.

**Comment by andrews05** [comment]
v9.1.3 is now up, complete with manpage.
