### ISSUE TITLE
OxiPNG stopped working on Windows 7

### ISSUE THREAD

**Issue by sergeevabc** [shssoichiro/oxipng#617]
Windows 7 x64.

OxiPNG 9.0.0 works fine, 9.1.0 does not.

![2024-0430-1353 oxipng 910 error](https://github.com/shssoichiro/oxipng/assets/373718/4f22e3b2-3837-4278-ad0d-3fcf28120662)

**Comment by andrews05** [comment]
Hi @sergeevabc 
Sorry to hear this. Can you post the file you're trying to optimise and the options you're using?

**Comment by sergeevabc** [comment]
@andrews05, it's not related to any graphic file, the app just refuses to run as is.

Perhaps Rust developers decided to betray Windows 7 users and the new version of the compiler simply does not allow you to make an executable file for this OS.

**Comment by andrews05** [comment]
It seems you are correct: https://github.com/rust-lang/compiler-team/issues/651
Windows 7 support was dropped in Rust 1.76, so our automated builds will no longer work on "legacy" platforms.

That said, oxipng's current MSRV is 1.74, so you could in fact build a working exe yourself.

**Comment by sergeevabc** [comment]
@andrews05, what do you mean “do it yourself”? I am a user, who is trained in another field, not a developer. This is your world, where I can only send signals.

**Comment by andrews05** [comment]
Apologies, I just mean that while it should be possible build v9.1 for Windows 7, this is not something we can provide for you. *Someone* could do it but the automated builds don't cater for this and I personally can't build for Windows myself.

You can of course continue to use v9.0 which is still a great version.
(Inevitably, some future release of oxipng will end up requiring Rust 1.76 or newer anyway, ruling out any possibility of building it for Windows 7.)

**Comment by AlexTMjugador** [comment]
I find it useful to note that the Rust compiler [later gained Tier 3 (i.e., barely tested and supported) targets for Windows 7](https://github.com/rust-lang/rust/pull/118150), though.

Anyway, adding Tier 3 targets to our CI opens a can of worms I'd prefer to keep closed. While the Rust compiler team does not have a strong reason to pull the plug for this Tier 3 target in particular for the time being, it's very likely that internal Rust changes end up introducing unintended dependencies on later Windows APIs that won't be noticed by anyone but final users, as there aren't any testing processes for Windows 7 anymore. I think that OxiPNG appearing to support Windows 7 when there's a non-negligible chance it really won't would cause even more frustration for both users and developers alike.

**Comment by AlexTMjugador** [comment]
rust9x is indeed interesting! For those willing to tinker with technical stuff, there's also [ReactOS](https://reactos.org/), an experimental OS that aims to achieve binary-compatibility with Windows applications and drivers, which at this point is arguably better supported by its creators than Windows 7.

Anyway, as stated above, I don't think it's in scope for OxiPNG to concern itself in an official capacity with targets that are effectively not supported by the build toolchain used. I'm closing this issue as not planned for now, but if there's anyone willing to go through what it takes to make Rust and, by proxy, OxiPNG well supported on Windows 7 again, please speak up and let us know for reopening this issue :+1:

**Comment by AlexTMjugador** [comment]
> I'm looking to bundle `oxipng` and assumed I could continue to support WinXP as a minimum OS supported.

For what it's worth, Rust hasn't supported Windows XP for years now, so if any recent OxiPNG version did ever work on XP it definitely was not intended. Did you ever have a chance of testing such a bundle with XP?
