### ISSUE TITLE
Unexpected --nx --nz behavior. Ignores interlaced images.

### ISSUE THREAD

**Issue by Galaxy4594** [shssoichiro/oxipng#619]
Environment: 
Windows 10 22H2

Flags `--nx --nz` should disable all optimizations for pngs right? It works on all images with one weird exception, interlaced pngs causes oxipng to ignore these flags and optimizes the image anyways. 

It seems that the default of `-i 0` automatically overrides everything else. It turns out you have to pass `--nx --nz -i keep` to truly disable all optimizations. The behavior should be so that `--nx --nz` alone keeps the images untouched regardless of them being interlaced or not.

![Screenshot](https://github.com/shssoichiro/oxipng/assets/164440799/d815a14a-ce12-4665-994e-25e1a0489f85)

**Comment by andrews05** [comment]
Hi @Galaxy4594, this is indeed a bug, `--nx` is supposed to disable the default deinterlacing too. I’ll try to get this fixed sometime.
