### ISSUE TITLE
-Z makes desktop unresponsive.

### ISSUE THREAD

**Issue by f2d** [shssoichiro/oxipng#63]
I took oxipng-v0.15.1-i686-pc-windows-msvc.zip release and tried oxipng with -Z option (zopfli), default thread count (i7-4770, 4+HT x 1.5 = 12 threads) and default process priority (Normal) on Windows 7 x64.

The program does not hang, but takes too long and system barely responds to anything, having trouble even redrawing anything on the desktop, except mouse pointer. After waiting around 8 minutes running on a single 200 KB file, i managed to kill it with Task Manager.

I continued testing after applying the lowest priority setting using a helpful menu from [https://habrahabr.ru/post/317802/](https://habrahabr.ru/post/317802/). Still takes pretty long even on small files, and seems to take longer than with single thread ("-t 1"), but no more troubles.

I think either x1.5 threads default is overkill for -Z, or the program needs to run with lower base priority implicitly.

Also a suggestion: interpret floating point like "-t 1.0" as multiplier to number of CPU cores.

**Comment by shssoichiro** [comment]
Oxipng should not actually be using the full 12 threads with -Z. At most, it should use 6, because there are only 6 trials needed (one for each filter mode). -Z is also known to be much slower than the default mode, simply because of the nature of zopfli. However, it shouldn't be taking several minutes for a small file (my benchmarks on an i7 were about 25 seconds for a 640x480 file), and this doesn't explain why you're seeing issues with the rest of your computer lagging. Can you verify that the machine has adequate memory and isn't swapping to disk when running oxipng?

**Comment by f2d** [comment]
I was watching oxipng in Process Explorer, which reported 13 threads and fully capped CPU usage graph, and the first test picture was pretty big, like 1600x800.

The machine had (and has) around 8 GB free memory and all files lying on RAMdisk, including swap, which should not be used anyway.

Here is process log from AnVir Task Manager (last run defaults to -t 12):
`03/21 17:23:47	oxipng.exe 8768 started by cmd.exe PC\user	E:\oxipng-v0.15.1-i686-pc-windows-msvc\oxipng.exe -v -Z -t 1 256x256.png
03/21 17:24:00	oxipng.exe 8768 terminated, worked 0:13, CPU 0:12
03/21 17:24:20	oxipng.exe 5824 started by cmd.exe PC\user	E:\oxipng-v0.15.1-i686-pc-windows-msvc\oxipng.exe -v -Z -t 6 256x256.png
03/21 17:24:33	oxipng.exe 5824 terminated, worked 0:11, CPU 1:07
03/21 17:24:49	oxipng.exe 7428 started by cmd.exe PC\user	E:\oxipng-v0.15.1-i686-pc-windows-msvc\oxipng.exe -v -Z 256x256.png
03/21 17:25:07	oxipng.exe 7428 terminated, worked 0:18, CPU 2:13

03/21 17:46:07	oxipng.exe 7852 started by cmd.exe PC\user	E:\oxipng-v0.15.1-x86_64-pc-windows-msvc\oxipng.exe -v -Z -t 1 256x256.png
03/21 17:46:19	oxipng.exe 7852 terminated, worked 0:10, CPU 0:10 
03/21 17:46:35	oxipng.exe 16132 started by cmd.exe PC\user	E:\oxipng-v0.15.1-x86_64-pc-windows-msvc\oxipng.exe -v -Z -t 6 256x256.png
03/21 17:46:43	oxipng.exe 16132 terminated, worked 0:08, CPU 0:45 
03/21 17:46:54	oxipng.exe 7548 started by cmd.exe PC\user	E:\oxipng-v0.15.1-x86_64-pc-windows-msvc\oxipng.exe -v -Z 256x256.png
03/21 17:47:12	oxipng.exe 7548 terminated, worked 0:18, CPU 2:17`

**Comment by f2d** [comment]
Reporting: it seems OK now.

Versions tried:
oxipng-v0.16.2-i686-pc-windows-msvc
oxipng-v0.16.2-x86_64-pc-windows-msvc

I have reset priority setting no normal and fed some big and small PNGs to oxipng.exe -Z without -t setting.
Process thread count was 13, CPU workload graph was corresponding to no more than 1-2 threads fully loaded at once.

No problems were encountered.

Should I try skipped previous versions, or just leave it at that?

**Comment by shssoichiro** [comment]
Interesting. Not much has changed between the two versions, but the bump in `rayon` from 0.6 to 0.8 seems like the most likely reason for this being fixed now.

I will close this, and if the issue returns in the future, feel free to report it here. Thanks!
