### ISSUE TITLE
Wrong Version either Reported or Packaged

### ISSUE THREAD

**Issue by Obscure2020** [shssoichiro/oxipng#637]
When I download `oxipng-9.1.2-x86_64-pc-windows-msvc.zip` from the Releases page, the `oxipng.exe` inside reports that it is version `9.1.1` when I run `oxipng -V`. This means that either you put version 9.1.1 in a package that was supposed to contain version 9.1.2, or it could mean that version 9.1.2 is erroneously programmed to report `9.1.1`.

**Comment by andrews05** [comment]
Hi @Obscure2020, sorry about this. I've just redeployed and it looks to be correct now.

(I think this happened because I deployed before the previous workflow had finished. It appeared to be affecting x86_64-windows as well as both the linux-musl packages.)

**Comment by AlexTMjugador** [comment]
> (I think this happened because I deployed before the previous workflow had finished. It appeared to be affecting x86_64-windows as well as both the linux-musl packages.)

Indeed, I can confirm the release deploy workflow is meant to be executed after the usual CI build for it finished, as otherwise it won't be able to fetch the proper binary artifact :+1:
