### ISSUE TITLE
`--zi` option is not recognized/supported

### ISSUE THREAD

**Issue by dustdfg** [shssoichiro/oxipng#651]
Tbh I even don't know if I use it correctly... Running `oxipng -o max --fast --zopfli --zi 30 --verbose logo.png` prints following error

```
error: unexpected argument '--zi' found

  tip: to pass '--zi' as a value, use '-- --zi'

Usage: oxipng --opt <level> --fast --zopfli <files>...

For more information, try '--help'.
```

If I run `oxipng --help` it doesn't list `--zi` option at all while it is present in [MANUAL.txt](https://github.com/shssoichiro/oxipng/blob/master/MANUAL.txt)

**Comment by andrews05** [comment]
Hi @dustdfg, I'm afraid we pushed an update to MANUAL.txt a little early. The `--zi` option is not yet available but will be coming in v9.1.3 which is imminent.

**Comment by dustdfg** [comment]
Oh, ok. Thanks for clarifying! I close it then

**Comment by TPS** [comment]
@andrews05 That syntax is _so_ wonky!  Is `-- --zi` meant to be correct?  I've a hunch I know why, but isn't there a way to smooth that out inline w/ the rest of the command-line options?

**Comment by dustdfg** [comment]
> @andrews05 That syntax is _so_ wonky! Is `-- --zi` meant to be correct? I've a hunch I know why, but isn't there a way to smooth that out inline w/ the rest of the command-line options?

Program didn't recognize `--zi` as option and told user: "I think that `--zi` is a filename which contains dashes. If it is really so, you can provide files which names start from dash after placing to dashes `oxipng <options> -- <filename-starting-from-dash>`"

**Comment by TPS** [comment]
Whoops, I completely misunderstood that.  But I believe the release that supports it is now out, @dustdfg.  Does it work as you intended above.

**Comment by dustdfg** [comment]
I haven't tried the release, but I am sure it works because I compiled master branch and used it directly
