### ISSUE TITLE
Some test files look dubious from a copyright/license perspective

### ISSUE THREAD

**Issue by musicinmybrain** [shssoichiro/oxipng#655]
While considering using the GitHub source archive as an additional source for Fedora’s `rust-oxipng` package due to https://github.com/shssoichiro/oxipng/issues/654, I noticed that several test files, such as [`issue-141.png`](https://github.com/shssoichiro/oxipng/blob/master/tests/files/issue-141.png), look like they may be based on copyrighted material not covered by oxipng’s MIT license.

In addition to any concerns that this might raise for oxipng redistributing these files on GitHub, this is a significant inconvenience for anyone – like a Linux distribution – who might have a reason to distribute source archives exported from GitHub, since these test files would need to be filtered out first.

Please consider auditing the contents of `tests/files` for license status, and attempting to replace those that may have license issues with “synthetic” test files that demonstrate the same issues.

**Comment by andrews05** [comment]
Thanks for bringing this up, it’s been in the back of my mind for some time now. I’ll get onto it.

**Comment by musicinmybrain** [comment]
Thank you for following up on this so quickly!
