### ISSUE TITLE
Implement possible size optimizations from Color Type from TruePNG

### ISSUE THREAD

**Issue by shssoichiro** [shssoichiro/oxipng#72]
https://css-ig.net/articles/truepng.php

> Colortype reductions
> TruePNG does some other trials that are not done automatically (or not done at all) by other tools:
>
- [x] TruePNG can test grayscale if image is graylevel
- [ ] it tests tRNS chunk instead of alpha channel if applicable
- [x] it reduces truecolor+alpha to grayscale+alpha
- [ ] it can choose truecolor, even if image contains less than 256 colors (or less)
- [ ] TruePNG can encode to palette mode even if image is graylevel

**Comment by fhanau** [comment]
I'm not sure if TruePNG does this, but oxipng should also try to do alpha reductions for palette images (for example by making all transparent pixels use the color of the first one, thus reducing palette size, trns chunk size and making the IDAT chunk more compressible).

**Comment by TPS** [comment]
@shssoichiro : #502 mentions that it fixes №4 in the top post.  Could that be checked off? 🙇🏾‍♂️
