### ISSUE TITLE
better parallelization, take IO wait into account

### ISSUE THREAD

**Issue by matthiaskrgr** [shssoichiro/oxipng#84]
Currently what oxipng seems to be doing is
````
load file from disk
check if it's a png
optimize in parallel
save file
load next file from disk
check if it's a png
optimize in parallel
...
````
It might be faster to run at least 2 compressions simultaneously to make IO traffic and cpu usage overlap, so that the cpu is busy compressing one image while the another one is already being loaded from the hard drive.

**Comment by andrews05** [comment]
Files are now processed in parallel in v9.
