### ISSUE TITLE
Optimizing all files in a folder on windows?

### ISSUE THREAD

**Issue by dragons4life** [shssoichiro/oxipng#90]
You are able to do this on truepng by simply using *.png, however in oxipng it thinks there is a file named *.png to be opened (but you can't even have a file named *.png), this is from the command line of course.

**Comment by shssoichiro** [comment]
Thanks for reporting this! I feel like this should work on Windows without needing to do anything special, but I can verify later today once I have access to a Windows machine.

**Comment by TPS** [comment]
In Windows, glob matching _isn't_ a function of the _OS_ (like *nixes), but of whatever matching library included in the _program_.

**Comment by shssoichiro** [comment]
Thanks, I didn't realize that. I usually don't develop on a Windows machine. I'll mark this as a bug to be fixed, then.

**Comment by TPS** [comment]
https://www.google.com/search?q=windows+rust+glob+matching finds https://doc.rust-lang.org/glob/, https://github.com/rust-lang-nursery/glob, &c, which might all be instructive.

**Comment by shssoichiro** [comment]
Sorry, I should have mentioned that this was fixed in 0.18.0.

**Comment by dragons4life** [comment]
It's fine, thanks for adding it.
