### ISSUE TITLE
Exit code is always zero?

### ISSUE THREAD

**Issue by potentcocktail** [shssoichiro/oxipng#93]
I haven't looked at the source, but it seems that even when an error occurs (such as an output file not being able to get created, or if an input file is not a PNG file) the exit code is always 0... This is a pretty big deal for me because my scripts check for errors by using exit codes to make sure things succeed normally.

**Comment by shssoichiro** [comment]
I agree overall but want to clarify an expectation. Oxipng processes files in a loop. If there is a batch optimization, say I run `oxipng *.png`, what would you expect the exit code to be if one file has an error but all others succeed? Should that be considered success or failure?

**Comment by CounterPillow** [comment]
optipng returns 1 if at least one file failed processing.

**Comment by shssoichiro** [comment]
That was my first thought as well but I wanted to make sure I wasn't completely off base. Released in v0.18.3.
